# Fase B — Pipeline ETL

**Proyecto 1 · Bodega de datos de siniestralidad vial en Cali (2016–2024)**

`[Integrantes del grupo N]` · RA1 · 30% de la nota

Este notebook implementa el pipeline **Extracción → Transformación → Carga** que
puebla la bodega dimensional diseñada en la **Fase A**. Al ejecutarlo queda
populada la base de datos PostgreSQL con:

- 1 tabla de hechos: `hecho_siniestralidad`
- 6 tablas de dimensión: `dim_fecha`, `dim_ubicacion`, `dim_tipo_accidente`,
  `dim_tipo_confirmado`, `dim_medio_reporte`, `dim_vehiculos_implicados`

**Cómo se ejecuta:** `Kernel → Restart & Run All`, de arriba abajo. El pipeline
es idempotente (usa `if_exists="replace"`), de modo que puede ejecutarse tantas
veces como sea necesario sin duplicar datos.

## El modelo que se construye

El diseño de la Fase A es un **modelo estrella**: una tabla de hechos central
rodeada de seis dimensiones, unidas por claves subrogadas.

```
                                dim_fecha
                       (fecha, anio, mes, trimestre)
                                   |
dim_ubicacion  ───┐                 |
(direccion)       │   ┌──────────────────────────┐   ┌──  dim_tipo_accidente
                  ├──▶│    hecho_siniestralidad  │◀──┤     (tipo_accidente)
dim_tipo_confirmado┘  │  - id_siniestro (PK)     │   └──  dim_medio_reporte
(tipo + detalle)     │  - codigo_reporte         │        (medio_reporte)
                     │  - numero_vehiculos ◀── MEDIDA
                     │  - id_fecha           (FK) │
                     │  - id_ubicacion       (FK) │
                     │  - id_tipo_accidente  (FK) │
                     │  - id_tipo_confirmado (FK) │
                     │  - id_medio_reporte   (FK) │
                     │  - id_vehiculos_impl. (FK) │
                     └──────────────────────────┘
                                   │
                      ┌────────────┴────────────┐
                      │                         │
        dim_vehiculos_implicados         (granularidad:
        (tipos_vehiculos)                UN reporte individual)
```

**Granularidad del hecho:** cada fila es **un reporte individual** de
siniestralidad, con su código, su fecha y sus 6 claves foráneas.

### Dos reglas de la bodega

1. **No se declara `FOREIGN KEY`.** En un modelo OLAP la relación existe en el
   diseño y se usa en los `JOIN`, pero no la impone el motor. Las razones: los
   datos pueden llegar antes que su dimensión, la validación en cargas masivas
   es costosa y la fuente emite códigos desconocidos.
2. **Patrón "Desconocido" (`id = -1`).** En lugar de dejar FK nulas, cada
   dimensión tiene una fila adicional con `id = -1` y el atributo
   `DESCONOCIDO`. Así el hecho siempre apunta a una fila válida y el bucket de
   datos faltantes puede analizarse explícitamente en la Fase C.

> **Sobre la medida.** `numero_vehiculos` llega con más de la mitad de sus
> valores en nulo y su disponibilidad **cambia según el año**. Decidimos
> **no imputar**: convertir "no sabemos cuántos vehículos" en `0` sería falsar
> el dato y sesgaría cualquier promedio. Se carga tal cual y se documenta
> como limitación. Las cifras exactas se calculan más abajo.

---
## 0. Configuración

Se cargan las librerías, se resuelven las rutas del proyecto y se lee
`DATABASE_URL` desde el archivo `.env`.

In [82]:
import os
import re
from pathlib import Path

import numpy as np
import pandas as pd
import sqlalchemy as sa
from dotenv import load_dotenv
from IPython.display import Markdown, display

def fmt(n):
    """Formatea un entero con separador de miles, para el texto generado."""
    return f"{int(n):,}"

try:
    import psycopg
except ImportError as error:
    raise RuntimeError(
        "Falta el driver de PostgreSQL 'psycopg' (version 3).\n\n"
        "Instalalo con:\n"
        '    pip install "psycopg[binary]"\n'
        "y revisa que este en requirements.txt."
    ) from error

print(f"pandas     {pd.__version__}")
print(f"SQLAlchemy {sa.__version__}")
print(f"psycopg    {psycopg.__version__}  (driver 'postgresql+psycopg')")

# --- Rutas -----------------------------------------------------------------
NOMBRE_CSV = "siniestralidad_2016_2024.csv"
CWD = Path.cwd().resolve()
RAIZ = CWD.parent if CWD.name == "entrega" else CWD

def _buscar(nombre, pista):
    """Busca 'nombre' en la raiz o en entrega/. 'pista' explica donde ponerlo."""
    candidatos = [RAIZ / nombre, RAIZ / "entrega" / nombre]
    for candidato in candidatos:
        if candidato.exists():
            return candidato.resolve()
    buscados = "\n".join(f"     {c.relative_to(RAIZ)}" for c in candidatos)
    raise FileNotFoundError(
        f"No se encontro '{nombre}'.\n\n"
        f"Se busco en:\n{buscados}\n\n"
        f"Para resolverlo:\n{pista}"
    )

PISTA_CSV = (
    "Coloque el archivo en la carpeta 'entrega/' del proyecto, con el nombre\n"
    f"     '{NOMBRE_CSV}'.\n"
    "Descarguelo de la fuente del curso y verifique que la codificacion sea\n"
    "     ISO-8859-1 (latin-1) y el separador ';'."
)
RUTA_CSV = _buscar(NOMBRE_CSV, PISTA_CSV)
print(f"\nCSV  : {RUTA_CSV.relative_to(RAIZ)}")

pandas     3.0.6
SQLAlchemy 2.1.1
psycopg    3.3.6  (driver 'postgresql+psycopg')

CSV  : entrega/siniestralidad_2016_2024.csv

In [83]:
# --- Credenciales ----------------------------------------------------------
RUTA_ENV = RAIZ / ".env"
if not RUTA_ENV.exists():
    raise FileNotFoundError(
        "No se encontro el archivo '.env' con la configuracion de la base.\n\n"
        "Se busco en:\n"
        f"     {RUTA_ENV.relative_to(RAIZ)}\n\n"
        "Para resolverlo:\n"
        "     cp .env.example .env\n"
        "y edita la linea DATABASE_URL con usuario, contrasena, host, puerto\n"
        "y base de datos."
    )

load_dotenv(RUTA_ENV)
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "El archivo .env existe pero no define la variable DATABASE_URL.\n\n"
        "Revisa que contenga una linea con esta forma:\n"
        "     DATABASE_URL=postgresql+psycopg://usuario:clave@host:puerto/base\n\n"
        "La plantilla .env.example trae los valores de ejemplo del curso."
    )

_url_segura = re.sub(r"://([^:/@]+):([^@]*)@", r"://\1:***@", DATABASE_URL)
print(f".env         : {RUTA_ENV.relative_to(RAIZ)}")
print(f"DATABASE_URL -> {_url_segura}")

.env         : .env
DATABASE_URL -> postgresql+psycopg://bodega:***@localhost:5433/siniestralidad

In [84]:
# --- Conexion con manejo de errores claros ---------------------------------
def _pista_de_conexion(detalle):
    """Traduce el mensaje del driver a una instruccion accionable."""
    d = detalle.lower()
    if "password authentication failed" in d:
        return "Usuario o contrasena incorrectos en DATABASE_URL."
    if "does not exist" in d and "database" in d:
        return ("La base de datos no existe. Creala con:\n"
                "    docker exec -it bodega-siniestralidad createdb -U bodega siniestralidad")
    if "password" in d and ("required" in d or "no password" in d):
        return "Falta la contrasena en la URL: Formato usuario:clave@host:puerto/base."
    if "connection refused" in d or "could not connect" in d or "no route to host" in d:
        return ("El servidor PostgreSQL no responde en ese puerto. Levanta el contenedor con:\n"
                "    docker start bodega-siniestralidad")
    if ("could not translate host name" in d or "name or service not known" in d
            or "nodename nor servname" in d or "name does not resolve" in d):
        return ("El host de DATABASE_URL no resuelve. Usa 'localhost' y no el nombre "
                "del contenedor: el puerto 5433 esta publicado en el host.")
    if "ssl" in d:
        return "Problema de SSL al conectar. Revisa que el contenedor use la clave de la clase."
    return "Revisa DATABASE_URL y que el contenedor este corriendo."

def crear_engine(database_url):
    """Crea el motor y lo prueba, explicando con precision que fallo."""
    try:
        motor = sa.create_engine(database_url, pool_pre_ping=True, future=True)
    except sa.exc.NoSuchModuleError as error:
        raise RuntimeError(
            "El nombre del driver en DATABASE_URL no es valido.\n\n"
            f"  Detalle: {error}\n\n"
            "  El driver de psycopg 3 se escribe 'postgresql+psycopg'. Si se tiene\n"
            "  psycopg2 instalado, el prefijo seria 'postgresql+psycopg2'.\n"
            "  URL actual: " + _url_segura
        ) from error
    except sa.exc.ArgumentError as error:
        raise RuntimeError(
            "DATABASE_URL esta mal formada.\n\n"
            f"  Detalle: {error}\n\n"
            "  Formato esperado:\n"
            "    postgresql+psycopg://usuario:clave@host:puerto/base_de_datos\n"
            "  URL actual: " + _url_segura
        ) from error

    try:
        with motor.connect() as conexion:
            conexion.execute(sa.text("SELECT 1"))
    except sa.exc.OperationalError as error:
        detalle = str(getattr(error, "orig", error)).strip().splitlines()[0]
        raise RuntimeError(
            "No se pudo conectar a PostgreSQL.\n\n"
            f"  Detalle : {detalle}\n"
            f"  Causa   : {_pista_de_conexion(detalle)}\n"
            f"  URL     : {_url_segura}"
        ) from error
    return motor

motor = crear_engine(DATABASE_URL)
with motor.connect() as conexion:
    version = conexion.execute(sa.text("SELECT version()")).scalar()
print(f"Conectado a {version.split(',')[0]}")

Conectado a PostgreSQL 17.10 (Debian 17.10-1.pgdg13+1) on x86_64-pc-linux-gnu

---
# Etapa E — Extracción

La extracción lee los datos **tal como están**, sin modificarlos. Este CSV tiene
tres particularidades que hacen que la lectura por defecto de pandas falle o
pierda información:

| Particularidad | Valor real | Qué pasa si se ignora |
|---|---|---|
| **Codificación** | ISO-8859-1 (latin-1) | `read_csv` usa UTF-8 y lanza `UnicodeDecodeError`, o reemplaza `ñ` por `?` |
| **Separador** | `;` y no `,` | toda la fila cae en una sola columna |
| **Nulos** | el literal `.` | se cuela como texto y contamina las categorías |

Además hay **dos pares de columnas con el mismo nombre** (`Tipo clase de
accidente` / `Tipo confirmado` repetidos). pandas las desambigua añadiéndoles
`.1`, y esa numeración hay que respetarla.

Y se lee **todo como texto** (`dtype=str`), igual que en la preclase: así pandas
no "adivina" tipos. Por ejemplo `Código` perdería ceros a la izquierda, y
`Numero vehículos` convertiría `'1.'` en `1.` y no en `1`.

In [85]:
# --- Constantes de extraccion ----------------------------------------------
SEPARADOR = ";"
CODIFICACION = "latin-1"        # ISO-8859-1: verificado, no hay bytes UTF-8
VARIANTES_NULAS = [".", "", " ", "-", "N/A", "NA", "NULO"]

FILAS_ESPERADAS = 371_003

df_raw = pd.read_csv(
    RUTA_CSV,
    sep=SEPARADOR,
    encoding=CODIFICACION,
    dtype=str,                              # todo como texto: la conversion es explicita
    na_values=VARIANTES_NULAS,              # '.' es el nulo real de esta fuente
    keep_default_na=True,
)

print(f"Extraidos: {len(df_raw):,} registros x {len(df_raw.columns)} columnas")
print("\nColumnas (pandas desambigua las repetidas con '.1'):")
for i, c in enumerate(df_raw.columns, 1):
    print(f"   {i:>2d}. {c}")

assert len(df_raw) == FILAS_ESPERADAS, (
    f"Se esperaban {FILAS_ESPERADAS:,} filas en el CSV crudo y se leyeron "
    f"{len(df_raw):,}. Revisa que el archivo no haya cambiado."
)
print(f"\nValidacion de integridad de la extraccion: OK ({FILAS_ESPERADAS:,} filas crudas)")

Extraidos: 371,003 registros x 10 columnas

Columnas (pandas desambigua las repetidas con '.1'):
    1. Código
    2. Fecha
    3. Tipo confirmado
    4. Dirección reporte
    5. Tipo clase de accidente
    6. Tipo clase de accidente.1
    7. Tipo confirmado.1
    8. Medio de reporte
    9. Numero vehículos
   10. Tipo de vehículos implicados

Validacion de integridad de la extraccion: OK (371,003 filas crudas)

In [86]:
df_raw.head(6)

,Código,Fecha,Tipo confirmado,Dirección reporte,Tipo clase de accidente,Tipo clase de accidente.1,Tipo confirmado.1,Medio de reporte,Numero vehículos,Tipo de vehículos implicados
0,96159,1/01/2016,Solo daños,Carrera 56 Con Calle 1 A,NaN,NaN,Solo Da?os,RADIO,2,MOTOCICLETA
1,96160,1/01/2016,Negativo,Calle 72 O Con Carrera 28 H,NaN,NaN,Negativo,RADIO,NaN,NaN
2,96161,1/01/2016,Con lesionado,Carrera 94 Con Calle 4 C,ATROPELLO,ATROPELLO,Por Atropello,TELEF?NICO 127,2,MOTOCICLETA
3,96162,1/01/2016,Con lesionado,Carrera 8 A Con Calle 44,VOLCAMIENTO,VOLCAMIENTO,Por Volcamiento,RADIO,1,MOTOCICLETA
4,96163,1/01/2016,Negativo,Carrera 28 H Con Calle 72 M,NaN,NaN,Negativo,TELEF?NICO 127,NaN,NaN
5,96164,1/01/2016,Solo daños,Carrera 46 C Con Calle 36,NaN,NaN,Solo Da?os,RADIO,2,"AUTOMOVIL,MOTOCICLETA"

---
# Etapa T — Diagnóstico previo

Antes de transformar conviene **mirar** qué se va a transformar. Aquí se
resuelven dos preguntas que la Fase A dejó abiertas y se cuantifica la calidad
de cada columna.

In [87]:
# --- Las dos columnas de nombre repetido, son duplicados de verdad? ---------
# Se comparan las dos columnas replicadas, no se tratan aparte.

def comparar(serie_a, serie_b):
    nulos_coinciden = serie_a.isna().equals(serie_b.isna())
    ambas_nulas = serie_a.isna() & serie_b.isna()
    diferencias = int(((serie_a != serie_b) & ~ambas_nulas).sum())
    return nulos_coinciden and diferencias == 0, diferencias, nulos_coinciden

COL_A, COL_B = "Tipo clase de accidente", "Tipo clase de accidente.1"
identicas, diferencias, nulos_ok = comparar(df_raw[COL_A], df_raw[COL_B])
print(f"'{COL_A}'  vs  '{COL_B}'")
print(f"   celdas no nulas que difieren .. {diferencias:,}")
print(f"   nulos en las mismas posiciones  {nulos_ok}")
print(f"   son identicas ................. {identicas}")
print("   -> Conclusion: es un duplicado exacto. Se conserva una sola columna.\n")

COL_A, COL_B = "Tipo confirmado", "Tipo confirmado.1"
identicas, diferencias, nulos_ok = comparar(df_raw[COL_A], df_raw[COL_B])
print(f"'{COL_A}'  vs  '{COL_B}'")
print(f"   celdas no nulas que difieren .. {diferencias:,}")
print(f"   nulos en las mismas posiciones  {nulos_ok}")
print(f"   son identicas ................. {identicas}")
print(f"   categorias reales distintas .. {df_raw[COL_A].nunique()} vs {df_raw[COL_B].nunique()}")
print("   -> Conclusion: NO son duplicados. Una es la clasificacion general y la")
print("      otra el detalle. Alimentan 'tipo_confirmado' + 'detalle_confirmado'.")

'Tipo clase de accidente'  vs  'Tipo clase de accidente.1'
   celdas no nulas que difieren .. 0
   nulos en las mismas posiciones  True
   son identicas ................. True
   -> Conclusion: es un duplicado exacto. Se conserva una sola columna.

'Tipo confirmado'  vs  'Tipo confirmado.1'
   celdas no nulas que difieren .. 158,615
   nulos en las mismas posiciones  False
   son identicas ................. False
   categorias reales distintas .. 6 vs 21
   -> Conclusion: NO son duplicados. Una es la clasificacion general y la
      otra el detalle. Alimentan 'tipo_confirmado' + 'detalle_confirmado'.

In [88]:
# --- Perfil de calidad por columna -----------------------------------------
perfil = pd.DataFrame({
    "nulos": df_raw.isna().sum(),
    "% nulos": (df_raw.isna().sum() / len(df_raw) * 100).round(2),
    "unicos": df_raw.nunique(),
})
perfil["% nulos"] = perfil["% nulos"].astype(str) + "%"
print(perfil.to_string())

UMBRAL_NARRATIVA = 40

print("\nValores mas frecuentes de las columnas de texto (detecta basura):")
for c in ["Tipo confirmado", "Tipo clase de accidente", "Medio de reporte",
          "Numero vehículos", "Tipo de vehículos implicados"]:
    print(f"\n   {c}:")
    for valor, n in df_raw[c].value_counts(dropna=False).head(6).items():
        if pd.isna(valor):
            texto = "NaN"
        elif len(str(valor)) > UMBRAL_NARRATIVA:
            texto = f"<texto de {len(str(valor))} caracteres, enmascarado>"
        else:
            texto = str(valor)
        print(f"      {n:>7,d}  {texto!r}")

                               nulos % nulos  unicos
Código                             1    0.0%  370998
Fecha                              1    0.0%    3229
Tipo confirmado                    3    0.0%       6
Dirección reporte             183686  49.51%   65334
Tipo clase de accidente       325258  87.67%      14
Tipo clase de accidente.1     325258  87.67%      14
Tipo confirmado.1              23389    6.3%      21
Medio de reporte              288099  77.65%      17
Numero vehículos              194424   52.4%      12
Tipo de vehículos implicados  222214   59.9%     843

Valores mas frecuentes de las columnas de texto (detecta basura):

   Tipo confirmado:
      246,110  'Negativo'
       73,828  'Solo daños'
       47,500  'Con lesionado'
        2,907  'Con fallecido'
          453  'Con fallecido (Foraneo)'
          202  'Solo Daños'

   Tipo clase de accidente:
      325,258  'NaN'
       20,548  'Choque'
       12,084  'CHOQUE'
        5,618  'ATROPELLO'
        2,819  'NO APLICA'
        1,350  'VOLCAMIENTO'

   Medio de reporte:
      288,099  'NaN'
       27,985  'TELEF?NICO 127'
       21,229  'CAD 123'
       20,039  'RADIO'
        5,836  'CAT 127'
        4,974  'AGENTE RADIO'

   Numero vehículos:
      194,424  'NaN'
      148,357  '2'
       19,028  '1'
        7,901  '3'
        1,069  '4'
          141  '5'

   Tipo de vehículos implicados:
      222,214  'NaN'
       38,832  'AUTOMOVIL,AUTOMOVIL'
       34,436  'AUTOMOVIL,MOTOCICLETA'
       13,501  'MOTOCICLETA'
        9,612  'AUTOMOVIL'
        7,865  'MOTOCICLETA,MOTOCICLETA'

## T0 — Limpieza mínima

Solo lo necesario para que el resto del pipeline sea confiable:

1. Descartar la **fila totalmente vacía** que hay al final del archivo (tiene
   vacíos hasta el código de reporte, no es un evento real).
2. Homogeneizar los nulos: ya vienen como `NaN` gracias a `na_values`.
3. **No** se borra ninguna fila que tenga al menos un dato. Un reporte sin
   dirección sigue siendo un reporte.

In [89]:
# --- T0: descartar la fila vacia -------------------------------------------
filas_crudas = len(df_raw)
df = df_raw.dropna(how="all").reset_index(drop=True)
descartadas_vacias = filas_crudas - len(df)

print(f"Filas antes           : {filas_crudas:,}")
print(f"Filas descartadas     : {descartadas_vacias}  (totalmente vacias)")
print(f"Filas despues         : {len(df):,}")
print(f"Codigos de reporte nulos tras la limpieza: {df['Código'].isna().sum()}")
assert len(df) > 0 and df["Código"].notna().all(), "Se perdio informacion en T0"
print("\nValidacion T0: OK")

Filas antes           : 371,003
Filas descartadas     : 1  (totalmente vacias)
Filas despues         : 371,002
Codigos de reporte nulos tras la limpieza: 0

Validacion T0: OK

In [90]:
# --- T0b: el codigo de reporte es unico? ----------------------------------
codigos_no_nulos = int(df["Código"].notna().sum())
codigos_unicos = int(df["Código"].nunique())
print(f"Codigos no nulos ..... {codigos_no_nulos:,}")
print(f"Codigos unicos ....... {codigos_unicos:,}")
print(f"Filas de mas .......... {codigos_no_nulos - codigos_unicos:,}")

repetidos = df["Código"].duplicated(keep=False)
print(f"\nFilas cuyo codigo esta repetido: {int(repetidos.sum()):,}")

if repetidos.any():
    filas_repetidas = df[repetidos]
    exactas = int(filas_repetidas.duplicated(keep=False).sum())
    print(f"   de ellas, identicas en las 10 columnas .. {exactas:,}")
    print(f"   de ellas, eventos distintos ............. "
          f"{int(repetidos.sum()) - exactas:,}")

    print("\nDetalle de los codigos repetidos (texto largo enmascarado):")
    detalle = filas_repetidas.copy()
    for c in detalle.columns:
        detalle[c] = detalle[c].map(
            lambda v: "<enmascarado>" if pd.notna(v) and len(str(v)) > UMBRAL_NARRATIVA else v)
    print(detalle.to_string(index=False))

Codigos no nulos ..... 371,002
Codigos unicos ....... 370,998
Filas de mas .......... 4

Filas cuyo codigo esta repetido: 8
   de ellas, identicas en las 10 columnas .. 8
   de ellas, eventos distintos ............. 0

Detalle de los codigos repetidos (texto largo enmascarado):
Código      Fecha Tipo confirmado  Dirección reporte  Tipo clase de accidente  Tipo clase de accidente.1 Tipo confirmado.1  Medio de reporte Numero vehículos Tipo de vehículos implicados
350723 27/02/2020      Solo daños                NaN                      NaN                        NaN    Arreglo Formal               NaN                2          AUTOMOVIL,AUTOMOVIL
350723 27/02/2020      Solo daños                NaN                      NaN                        NaN    Arreglo Formal               NaN                2          AUTOMOVIL,AUTOMOVIL
354438  5/04/2020        Negativo                NaN                      NaN                        NaN          Negativo               NaN                2                          NaN
354438  5/04/2020        Negativo                NaN                      NaN                        NaN          Negativo               NaN                2                          NaN
361442  8/08/2020        Negativo                NaN                      NaN                        NaN          Negativo               NaN              NaN                          NaN
361442  8/08/2020        Negativo                NaN                      NaN                        NaN          Negativo               NaN              NaN                          NaN
361474  8/08/2020        Negativo                NaN                      NaN                        NaN          Negativo               NaN              NaN                          NaN
361474  8/08/2020        Negativo                NaN                      NaN                        NaN          Negativo               NaN              NaN                          NaN

In [91]:
# --- T0c: decision sobre los duplicados exactos ----------------------------

codigos_no_nulos = int(df["Código"].notna().sum())
codigos_unicos = int(df["Código"].nunique())
duplicados_exactos = int(df[df["Código"].duplicated(keep=False)].duplicated(keep=False).sum())

CODIGO_ES_UNICO = True

if not CODIGO_ES_UNICO:
    raise AssertionError("decision pendiente: implementada la rama de conservar")

# Evidencia de que las repetidas son identicas en todas sus columnas.
_repetidas = df[df.duplicated(keep=False)]
_distintas = _repetidas.drop_duplicates()
_n_repetidas = len(_repetidas)
_n_unicas_entre_repetidas = len(_distintas)
assert _n_unicas_entre_repetidas > 0, (
    "Hay codigos repetidos pero ninguna fila resulta identica a otra: entonces "
    "no son duplicados exactos y no se deben eliminar."
)
_exceso = _n_repetidas - _n_unicas_entre_repetidas

df = df.drop_duplicates().reset_index(drop=True)
eliminadas = codigos_no_nulos - len(df)

assert eliminadas == _exceso, (
    f"Se eliminaron {eliminadas} filas pero habia {_exceso} duplicados exactos. "
    "Si no coinciden, 'drop_duplicates' esta tocando filas que no debian."
)
print(f"   filas con codigo repetido ................. {_n_repetidas:,}")
print(f"   combinaciones distintas entre ellas ....... {_n_unicas_entre_repetidas:,}")
print(f"   duplicados EXACTOS a eliminar ............ {_exceso:,}")

FILAS_ESPERADAS_HECHO = 370_998

print(f"Filas tras eliminar duplicados exactos: {len(df):,}  (-{eliminadas:,})")
assert len(df) == FILAS_ESPERADAS_HECHO, (
    f"Se esperaban {FILAS_ESPERADAS_HECHO:,} filas en el hecho y hay {len(df):,}. "
    "El CSV pudo cambiar."
)
assert df["Código"].is_unique, "El codigo de reporte sigue sin ser unico"
print(f"\nValidacion T0c: OK. 'Código' es ahora unico en las {len(df):,} filas.")
print("  -> 'codigo_reporte' queda como clave natural del hecho (dimension degenerada),")
print("     y 'id_siniestro' como clave subrogada (PK).")

   filas con codigo repetido ................. 8
   combinaciones distintas entre ellas ....... 4
   duplicados EXACTOS a eliminar ............ 4
Filas tras eliminar duplicados exactos: 370,998  (-4)

Validacion T0c: OK. 'Código' es ahora unico en las 370,998 filas.
  -> 'codigo_reporte' queda como clave natural del hecho (dimension degenerada),
     y 'id_siniestro' como clave subrogada (PK).

## T1 — Normalización de textos

Esta es la parte con más sustancia del ETL, porque la fuente tiene **mojibake**.

### El problema

El archivo mezcla dos estados distintos:

- unas **75 mil células** conservan el acento correcto en latin-1 (`Solo daños`)
- otras **85 mil células** perdieron el acento y dejaron un `?` literal
  (`Solo Da?os`)

Ese `?` se produjo en una exportación previa y **ya no es recuperable desde el
archivo**. Lo que sí puede hacerse es reconstruirlo con un diccionario.

### Por qué `?` → `Ñ` global es un error

Lo primero que se intenta es reemplazar el carácter. **Falla**, porque el `?`
reemplaza letras distintas según la palabra:

| Valor crudo | el `?` reemplaza… | Reparación correcta | Resultado con `?`→`Ñ` |
|---|---|---|---|
| `Ca?da Ocupante` | la `í` de "caída" | `CAIDA` | `CANDA` ❌ |
| `No Quiere Intervenci?n` | la `ó` de "intervención" | `INTERVENCION` | `INTERVENCINN` ❌ |
| `Da?os` | la `ñ` de "daños" | `DAÑOS` | `DANOS` ✅ |

Además hay **variantes de espaciado** que una normalización genérica no puede
arreglar porque no sabe dónde va el espacio: `NOAPLICA` vs `NO APLICA`,
`TELEF?NICO127` vs `TELEF?NICO 127`, `NOQUIEREINTERVENCION` vs
`NO QUIERE INTERVENCION`.

### La solución

Un **diccionario explícito**, ordenado de la clave más larga a la más corta
para que el caso específico gane sobre el genérico. Después se aplica una
normalización uniforme y determinista:

1. `strip` + colapsar espacios + `upper`
2. diccionario de reparación (más específico primero)
3. **proteger la `Ñ`**, que es la única tilde que no es un diacrítico
4. descomponer (`NFKD`) y quitar los diacríticos
5. **restaurar la `Ñ`** y colapsar espacios de nuevo

### Por qué la `Ñ` se protege en vez de quitarse como las demás

Los pasos 3 y 5 son necesarios porque `Ñ` **no es una tilde sino una letra
distinta**: `DAÑOS` y `DANOS` no son la misma palabra. El NFKD la parte en `N` +
tilde combinante, y al quitar los diacríticos se perdía el cedillo, dejando
`SOLO DANOS` en vez de `SOLO DAÑOS`. Con la protección, los dos caminos de la
fuente convergen igual:

| Entrada | Camino | Resultado |
|---|---|---|
| `Solo daños` | tilde real | `SOLO DAÑOS` |
| `Solo Da?os` | mojibake → diccionario | `SOLO DAÑOS` |
| `DA??OS` | mojibake → diccionario | `DAÑOS` |

In [92]:
# --- Diccionario de reparacion ---------------------------------------------
MAPA_REPARACION = {
    # --- medio de reporte: el '?' es la ONCE de 'TELEFONICO'
    "TELEF?NICO127":        "TELEFONICO 127",
    "TELEF?NICO 127":       "TELEFONICO 127",
    # --- medio de reporte: faltan espacios, no hay mojibake
    "CAD123":               "CAD 123",
    "AGENTE TRACR":         "AGENTE TRAC",
    # --- tipo de accidente: '?' es la I con tilde de 'CAIDA'
    "CA?DA DE OCUPANTE":    "CAIDA DE OCUPANTE",
    "CA?DA OCUPANTE":       "CAIDA DE OCUPANTE",
    "CA?DA":                "CAIDA",
    # --- tipo de accidente: 'DA?OS' y 'DA??OS' traen la ENE, no un diacritico
    "DA??OS":               "DAÑOS",
    "DA?OS":                "DAÑOS",
    # --- tipo de accidente: variante sin espacio
    "NOAPLICA":             "NO APLICA",
    # --- detalle confirmado: aqui el '?' sustituye la O de 'intervencion', por
    "INTERVENCI?N":         "INTERVENCION",
    # --- detalle confirmado: variante pegada, sin espacios. Sin esta regla
    "NOQUIEREINTERVENCION": "NO QUIERE INTERVENCION",
}
CLAVES_ORDENADAS = sorted(MAPA_REPARACION, key=len, reverse=True)

#   'INTERVENCI?N' -> 'NOQUIEREINTERVENCION' -> 'NO QUIERE INTERVENCION' (3 pasos)
MAX_PASADAS = 5
print(f"Diccionario: {len(MAPA_REPARACION)} reglas, aplicadas de mas larga a mas corta:")
for clave in CLAVES_ORDENADAS:
    print(f"   {clave:<24s} -> {MAPA_REPARACION[clave]}")

MARCA_ENE = "\u0001"

CATALOGOS = ["Tipo confirmado", "Tipo confirmado.1",
             "Tipo clase de accidente", "Medio de reporte"]

def normalizar_texto(serie):
    """Limpia y estandariza una serie de texto. Vectorizada, sin apply().

    El diccionario se aplica hasta punto fijo: ver la nota de MAX_PASADAS.
    """
    s = serie.astype("string")
    s = s.str.strip().str.replace(r"\s+", " ", regex=True).str.upper()
    for _ in range(MAX_PASADAS):
        antes = s
        for clave in CLAVES_ORDENADAS:
            s = s.str.replace(clave, MAPA_REPARACION[clave], regex=False)
        if s.equals(antes):
            break
    else:
        raise AssertionError(
            f"El diccionario de reparacion no convergio en {MAX_PASADAS} pasadas: "
            "hay una regla que reintroduce una clave ya aplicada."
        )
    s = s.str.replace("Ñ", MARCA_ENE, regex=False)
    s = s.str.normalize("NFKD").str.replace(r"[\u0300-\u036f]", "", regex=True)
    s = s.str.replace(MARCA_ENE, "Ñ", regex=False)
    return s.str.replace(r"\s+", " ", regex=True).str.strip()

bruto = pd.Series(sorted(df["Tipo confirmado.1"].dropna().unique()))
normalizado_bruto = normalizar_texto(bruto)
cambiados = bruto.ne(normalizado_bruto)

solo_mayusculas = bruto.str.upper()
reparadas_por_diccionario = bruto.ne(solo_mayusculas) & cambiados

# La tabla usa la misma mascara que se reporta; si no, las filas se descuadran.
reparacion = pd.DataFrame({
    "crudo": bruto[reparadas_por_diccionario].values,
    "solo_mayusculas": solo_mayusculas[reparadas_por_diccionario].values,
    "con_diccionario": normalizado_bruto[reparadas_por_diccionario].values,
})

# El .upper() cambia el texto pero NO repara el mojibake.
_solo_upper = int(bruto.ne(solo_mayusculas).sum())
_solo_dicc = int(reparadas_por_diccionario.sum())
_solo_mayus = int((bruto.ne(solo_mayusculas) & ~cambiados).sum())
assert len(reparacion) == _solo_dicc, (
    f"La tabla tiene {len(reparacion)} filas pero se reportan {_solo_dicc} "
    "categorias reparadas: la mascara y la tabla no son la misma."
)
assert _solo_upper == _solo_mayus + _solo_dicc, (
    f"El .upper() cambia {_solo_upper} categorias, pero {_solo_mayus} son solo "
    f"mayusculas y {_solo_dicc} son del diccionario: {_solo_mayus + _solo_dicc} "
    "en total. Las dos causas deben sumar exactamente el total."
)

print(f"\nDe {len(bruto)} categorias distintas de 'Tipo confirmado.1':")
print(f"   el .upper() las cambia ............. {_solo_upper:,}  (no repara nada)")
print(f"     de esas, solo por mayusculas ..... {_solo_mayus:,}")
print(f"     de esas, ademas por el diccionario {_solo_dicc:,}  <- el efecto real")
print(f"\nValores realmente reparados por el diccionario ({_solo_dicc} categorias):")
print(reparacion.to_string(index=False))
prueba_ene = pd.Series(["Solo daños", "Solo Daños", "Da?os", "DA??OS"])
print("\nVerificacion de la ENE (tilde real y mojibake deben converger):")
print("   " + " | ".join(f"{v!r} -> {normalizar_texto(pd.Series([v])).iloc[0]!r}"
                        for v in prueba_ene))

_textos = pd.concat([normalizar_texto(df[c]) for c in CATALOGOS], ignore_index=True)
assert not _textos.str.contains(MARCA_ENE, regex=False).any(), \
    "Quedo el marcador de la ENE en la salida de la normalizacion"
print(f"   marcador de proteccion: ausente en las {_textos.notna().sum():,} celdas de texto")

Diccionario: 12 reglas, aplicadas de mas larga a mas corta:
   NOQUIEREINTERVENCION     -> NO QUIERE INTERVENCION
   CA?DA DE OCUPANTE        -> CAIDA DE OCUPANTE
   TELEF?NICO 127           -> TELEFONICO 127
   CA?DA OCUPANTE           -> CAIDA DE OCUPANTE
   TELEF?NICO127            -> TELEFONICO 127
   AGENTE TRACR             -> AGENTE TRAC
   INTERVENCI?N             -> INTERVENCION
   NOAPLICA                 -> NO APLICA
   CAD123                   -> CAD 123
   DA??OS                   -> DAÑOS
   CA?DA                    -> CAIDA
   DA?OS                    -> DAÑOS

De 21 categorias distintas de 'Tipo confirmado.1':
   el .upper() las cambia ............. 15  (no repara nada)
     de esas, solo por mayusculas ..... 0
     de esas, ademas por el diccionario 15  <- el efecto real

Valores realmente reparados por el diccionario (15 categorias):
                                        crudo                               solo_mayusculas                               con_diccionario
                               Arreglo Formal                                ARREGLO FORMAL                                ARREGLO FORMAL
                        Choque con Lesionados                         CHOQUE CON LESIONADOS                         CHOQUE CON LESIONADOS
                                   Embriaguez                                    EMBRIAGUEZ                                    EMBRIAGUEZ
                                 Falsa Alarma                                  FALSA ALARMA                                  FALSA ALARMA
                         Inspeccion a Cadaver                          INSPECCION A CADAVER                          INSPECCION A CADAVER
Lesiones (Humano golpea vehiculo estacionado) LESIONES (HUMANO GOLPEA VEHICULO ESTACIONADO) LESIONES (HUMANO GOLPEA VEHICULO ESTACIONADO)
                             Muerto en la via                              MUERTO EN LA VIA                              MUERTO EN LA VIA
                                     Negativo                                      NEGATIVO                                      NEGATIVO
                       No Quiere Intervenci?n                        NO QUIERE INTERVENCI?N                        NO QUIERE INTERVENCION
                         NoQuiereIntervenci?n                          NOQUIEREINTERVENCI?N                        NO QUIERE INTERVENCION
                                Por Atropello                                 POR ATROPELLO                                 POR ATROPELLO
                        Por Caida de Ocupante                         POR CAIDA DE OCUPANTE                         POR CAIDA DE OCUPANTE
                              Por Volcamiento                               POR VOLCAMIENTO                               POR VOLCAMIENTO
                                Procedimiento                                 PROCEDIMIENTO                                 PROCEDIMIENTO
                                   Solo Da?os                                    SOLO DA?OS                                    SOLO DAÑOS

Verificacion de la ENE (tilde real y mojibake deben converger):
   'Solo daños' -> 'SOLO DAÑOS' | 'Solo Daños' -> 'SOLO DAÑOS' | 'Da?os' -> 'DAÑOS' | 'DA??OS' -> 'DAÑOS'
   marcador de proteccion: ausente en las 847,255 celdas de texto

In [93]:
# --- PII en 'Medio de reporte' ---------------------------------------------
# 'where' con condicion NA reemplaza el NA: por eso el ETL usa 'mask'.

narrativas = df["Medio de reporte"].fillna("").str.len() > UMBRAL_NARRATIVA
print(f"Celdas de 'Medio de reporte' con texto largo (posible narrativa/PII): "
      f"{int(narrativas.sum())}")
print("\nCodigos de reporte afectados y su largo:")
for codigo, largo in df.loc[narrativas, ["Código", "Medio de reporte"]].assign(
        n=lambda d: d["Medio de reporte"].str.len()).set_index("Código")["n"].items():
    print(f"   {codigo}  ({largo} caracteres)")

print("\n-> Se remapean a 'OTRO'. No se imprime su contenido para no exponer PII.")

Celdas de 'Medio de reporte' con texto largo (posible narrativa/PII): 5

Codigos de reporte afectados y su largo:
   AI0001827  (52 caracteres)
   AI0002037  (932 caracteres)
   AI002378  (647 caracteres)
   AI002973  (161 caracteres)
   AI003109  (492 caracteres)

-> Se remapean a 'OTRO'. No se imprime su contenido para no exponer PII.

### T1b — Marco de trabajo

Se construye un solo DataFrame `w` con las columnas ya normalizadas y con los
nombres de la Fase A. A partir de aquí, tanto las dimensiones como el hecho se
derivan de `w`, lo que evita transformaciones repetidas y garantiza que ambos
usen exactamente las mismas claves.

### Tres decisiones de fondo que se toman aquí

1. **Un nulo no se convierte nunca en un valor inventado.** Si el dato falta, la
   columna queda nula y la fila termina en la centinela `-1` de su dimensión.
   Esto aplica a `medio_reporte` (C1) y a `tipo_accidente` (D1).
2. **Un dato parcial sí se conserva.** Si `Tipo confirmado` tiene valor pero
   `Tipo confirmado.1` no, el hecho tiene clasificación general y lo que falta es
   el detalle. Eso se marca `SIN DETALLE` (C2), no `DESCONOCIDO`: son cosas
   distintas y colapsarlas perdería información.
3. **Un "no aplica" se distingue de un "no sé".** Un reporte `NEGATIVO` no
   tuvo accidente, así que la ausencia de tipo de accidente es *estructural*, no
   un dato perdido. Se etiqueta aparte (D1).

In [94]:
ETIQUETA_SIN_DETALLE = "SIN DETALLE"
ETIQUETA_SIN_ACCIDENTE = "SIN ACCIDENTE (NEGATIVO)"
ETIQUETA_NO_APLICA = "NO APLICA"
ETIQUETA_OTRO = "OTRO"

NOMBRE_DESCONOCIDO = "DESCONOCIDO"

ETIQUETAS_CENTINELA_VEHICULOS = {ETIQUETA_SIN_ACCIDENTE, NOMBRE_DESCONOCIDO}

w = pd.DataFrame(index=df.index)

ORIGEN_A_MODELO = {
    "Código": "codigo_reporte",
    "Fecha": "fecha",
    "Dirección reporte": "direccion_reporte",
    "Tipo clase de accidente": "tipo_accidente",
    "Tipo confirmado": "tipo_confirmado",
    "Tipo confirmado.1": "detalle_confirmado",
    "Medio de reporte": "medio_reporte",
    "Tipo de vehículos implicados": "tipos_vehiculos",
    "Numero vehículos": "numero_vehiculos",
}

w["codigo_reporte"] = df["Código"]

FECHA_INVALIDA = pd.to_datetime(df["Fecha"], format="%d/%m/%Y", errors="coerce")
n_fechas_invalidas = int(FECHA_INVALIDA.isna().sum())
print(f"Fechas no parseables: {n_fechas_invalidas}")
print(f"Rango: {FECHA_INVALIDA.min().date()} -> {FECHA_INVALIDA.max().date()}")
w["fecha"] = FECHA_INVALIDA

# --- Dimensiones de texto --------------------------------------------------
w["direccion_reporte"] = normalizar_texto(df["Dirección reporte"])
w["tipo_accidente"] = normalizar_texto(df["Tipo clase de accidente"])
w["tipo_confirmado"] = normalizar_texto(df["Tipo confirmado"])

# --- C2: el detalle falta, pero la clasificacion general no ----------------
detalle = normalizar_texto(df["Tipo confirmado.1"])
sin_detalle = detalle.isna() & w["tipo_confirmado"].notna()
w["detalle_confirmado"] = detalle.mask(sin_detalle, ETIQUETA_SIN_DETALLE)
print(f"\nC2 - filas con clasificacion general y sin detalle -> "
      f"'{ETIQUETA_SIN_DETALLE}': {int(sin_detalle.sum()):,}")
print(f"    filas sin clasificacion general (van a -1):     "
      f"{int(w['tipo_confirmado'].isna().sum()):,}")

# --- D1: el 'NO APLICA' de la fuente, antes de mezclar nada ---------------
es_no_aplica_fuente = w["tipo_accidente"] == ETIQUETA_NO_APLICA
print(f"\nD1 - 'NO APLICA' que trae la fuente: {int(es_no_aplica_fuente.sum()):,} filas")
print("    Cruce de esas filas con 'Tipo confirmado':")
cruce_no_aplica = pd.crosstab(
    w.loc[es_no_aplica_fuente, "tipo_confirmado"].fillna("<sin clasificacion>"),
    columns="filas",
)
print(cruce_no_aplica.to_string())

# --- C1: 'Medio de reporte' -----------------------------------------------
medio = normalizar_texto(df["Medio de reporte"])
es_narrativa = medio.str.len().fillna(0) > UMBRAL_NARRATIVA
w["medio_reporte"] = medio.mask(es_narrativa, ETIQUETA_OTRO)
print(f"\nC1 - celdas anonimizadas a '{ETIQUETA_OTRO}' (narrativas): "
      f"{int(es_narrativa.sum()):,}")
print(f"    nulos de 'Medio de reporte' conservados: "
      f"{int(w['medio_reporte'].isna().sum()):,}")

# --- D3: dos categorias 'otro' distintas -----------------------------------
OTROS_FUENTE = {"OTRO", "OTRO VALOR"}
# El conteo va sobre 'medio' (pre-mask): si no, las narrativas se cuentan dos veces.
es_otro_fuente = medio.isin(OTROS_FUENTE)
n_otro_fuente = int(es_otro_fuente.sum())
n_otro_fuente_y_narrativa = int((es_otro_fuente & es_narrativa).sum())
n_otro_fuente_solo = n_otro_fuente - n_otro_fuente_y_narrativa
print(f"\nD3 - 'otro' de la fuente: {n_otro_fuente_solo:,} filas "
      f"('OTRO' / 'OTRO VALOR')")
print(f"    de las cuales ya eran narrativas y C1 las habia remapeado: "
      f"{n_otro_fuente_y_narrativa:,}")
print(f"    narrativas anonimizadas que no venian de la fuente: "
      f"{int(es_narrativa.sum()) - n_otro_fuente_y_narrativa:,}")
w["medio_reporte"] = w["medio_reporte"].mask(es_otro_fuente, ETIQUETA_OTRO)
print(f"    '{ETIQUETA_OTRO}' recibira en total "
      f"{int((w['medio_reporte'] == ETIQUETA_OTRO).sum()):,} filas")

Fechas no parseables: 0
Rango: 2016-01-01 -> 2024-11-02

C2 - filas con clasificacion general y sin detalle -> 'SIN DETALLE': 23,388
    filas sin clasificacion general (van a -1):     2

D1 - 'NO APLICA' que trae la fuente: 2,885 filas
    Cruce de esas filas con 'Tipo confirmado':
col_0                    filas
tipo_confirmado
CON FALLECIDO               57
CON FALLECIDO (FORANEO)     21
CON LESIONADO              216
NEGATIVO                  2111
SOLO DAÑOS                 480

C1 - celdas anonimizadas a 'OTRO' (narrativas): 5
    nulos de 'Medio de reporte' conservados: 288,094

D3 - 'otro' de la fuente: 9 filas ('OTRO' / 'OTRO VALOR')
    de las cuales ya eran narrativas y C1 las habia remapeado: 0
    narrativas anonimizadas que no venian de la fuente: 5
    'OTRO' recibira en total 14 filas

In [95]:
# 'NO APLICA' de la fuente NO se fusiona con el nulo estructural.
es_negativo = (w["tipo_confirmado"] == "NEGATIVO").fillna(False)
assert not es_negativo.isna().any(), (
    f"quedan {int(es_negativo.isna().sum())} filas con condicion NA en "
    "es_negativo: el .mask() las trataria como True y volveria el bug."
)
sin_tipo_por_negativo = w["tipo_accidente"].isna() & es_negativo
assert not sin_tipo_por_negativo.isna().any(), (
    f"quedan {int(sin_tipo_por_negativo.sum())} filas con condicion NA en "
    "sin_tipo_por_negativo: el .mask() las trataria como True."
)
w["tipo_accidente"] = w["tipo_accidente"].mask(
    sin_tipo_por_negativo, ETIQUETA_SIN_ACCIDENTE)

nulo_tipo = w["tipo_accidente"].isna()
print(f"D1 - reporte NEGATIVO y sin tipo de accidente -> "
      f"'{ETIQUETA_SIN_ACCIDENTE}': {int(sin_tipo_por_negativo.sum()):,}")
print(f"    nulos que quedan como faltante real (van a -1): "
      f"{int(nulo_tipo.sum()):,}")

crudo_vehiculos = df["Tipo de vehículos implicados"]
print("    El mismo cruce para 'Tipo de vehiculos implicados':")
nulo_veh = crudo_vehiculos.isna()
etiqueta_veh = nulo_veh.map({True: "sin vehiculo", False: "con vehiculo"})
cruce_veh = pd.crosstab(
    w["tipo_confirmado"].fillna("<sin clasificacion>"),
    etiqueta_veh,
)
cruce_veh["% sin vehiculo"] = (
    cruce_veh["sin vehiculo"] / cruce_veh.sum(axis=1) * 100).round(1)
print(cruce_veh.to_string())

D1 - reporte NEGATIVO y sin tipo de accidente -> 'SIN ACCIDENTE (NEGATIVO)': 227,937
    nulos que quedan como faltante real (van a -1): 97,316
    El mismo cruce para 'Tipo de vehiculos implicados':
Tipo de vehículos implicados  con vehiculo  sin vehiculo  % sin vehiculo
tipo_confirmado
<sin clasificacion>                      0             2           100.0
CON FALLECIDO                         1246          1661            57.1
CON FALLECIDO (FORANEO)                257           196            43.3
CON LESIONADO                        40013          7487            15.8
NEGATIVO                             47080        199027            80.9
SOLO DAÑOS                           60192         13837            18.7

In [96]:
# --- D1b: la misma regla estructural para los vehiculos --------------------
sin_veh_por_negativo = crudo_vehiculos.isna() & es_negativo
assert not sin_veh_por_negativo.isna().any(), (
    f"quedan {int(sin_veh_por_negativo.isna().sum())} filas con condicion NA "
    "en sin_veh_por_negativo: es la misma trampa de NA que en D1."
)
print(f"\nD1b - reporte NEGATIVO y sin tipo de vehiculo -> "
      f"'{ETIQUETA_SIN_ACCIDENTE}': {int(sin_veh_por_negativo.sum()):,}")
print(f"    nulos que quedan como faltante real (van a -1): "
      f"{int((~sin_veh_por_negativo & crudo_vehiculos.isna()).sum()):,}")

D1b - reporte NEGATIVO y sin tipo de vehiculo -> 'SIN ACCIDENTE (NEGATIVO)': 199,027
    nulos que quedan como faltante real (van a -1): 23,183

In [97]:
# --- Combinaciones canonicas de vehiculos ----------------------------------

VALORES_SIN_SIGNIFICADO = {"DESCONOCIDO", "DESCONOCIDA", "SIN CLASE", "NO APLICA"}

def _canonizar_vehiculos(valor):
    if pd.isna(valor):
        return pd.NA
    tokens = []
    for bruto in str(valor).split(","):
        token = re.sub(r"\s+", " ", bruto.strip().strip('"')).strip().upper()
        if not token or token in VALORES_SIN_SIGNIFICADO or token.isdigit():
            continue
        tokens.append(token)
    return ", ".join(sorted(tokens)) if tokens else pd.NA

tokens_por_fila = crudo_vehiculos.dropna().map(
    lambda v: [re.sub(r"\s+", " ", b.strip().strip('"')).strip().upper()
               for b in str(v).split(",")])
tokens_numericos = tokens_por_fila.map(
    lambda ts: [t for t in ts if t and t.isdigit()])
n_filas_con_numerico = int(tokens_numericos.map(bool).sum())
n_tokens_numericos = int(tokens_numericos.map(len).sum())
w["tipos_vehiculos"] = crudo_vehiculos.map(_canonizar_vehiculos)
n_veh_a_na = int((crudo_vehiculos.notna() & w["tipos_vehiculos"].isna()).sum())

print(f"\nC4 - filas con al menos un token numerico: {n_filas_con_numerico:,} "
      f"({n_tokens_numericos:,} tokens)")
print(f"    filas que quedan sin ningun token valido: {n_veh_a_na:,}")
print(f"Combinaciones de vehiculos: {int(crudo_vehiculos.nunique()):,} crudas -> "
      f"{int(w['tipos_vehiculos'].nunique()):,} canonicas")

w["tipos_vehiculos"] = w["tipos_vehiculos"].mask(
    w["tipos_vehiculos"].isna() & es_negativo, ETIQUETA_SIN_ACCIDENTE)
# Informada pero sin token valido: no es lo mismo que vacia.
print(f"\n    reportes NEGATIVO sin ningun token valido -> "
      f"'{ETIQUETA_SIN_ACCIDENTE}': "
      f"{int((w['tipos_vehiculos'] == ETIQUETA_SIN_ACCIDENTE).sum()):,}")
print(f"    (el cruce anterior contaba solo celdas vacias: "
      f"{int((nulo_veh & es_negativo).sum()):,})")

C4 - filas con al menos un token numerico: 5 (5 tokens)
    filas que quedan sin ningun token valido: 8
Combinaciones de vehiculos: 843 crudas -> 733 canonicas

    reportes NEGATIVO sin ningun token valido -> 'SIN ACCIDENTE (NEGATIVO)': 199,031
    (el cruce anterior contaba solo celdas vacias: 199,027)

In [98]:
# --- Medida: 'Numero vehiculos' --------------------------------------------
crudos_num = df["Numero vehículos"]
con_punto = crudos_num.dropna().str.contains(r"\.")
valores_con_punto = crudos_num.dropna()[con_punto].value_counts()
print("Valores de 'Numero vehiculos' con formato anomalo: "
      f"{int(con_punto.sum())}")
print("   valores encontrados: " + ", ".join(repr(v) for v in valores_con_punto.index))

malformados = crudos_num.dropna()[con_punto & ~crudos_num.dropna().str.fullmatch(r"\d+\.")]
assert len(malformados) == 0, (
    f"Hay {len(malformados)} valores numericos malformados que rstrip no "
    f"corrige con seguridad: {sorted(set(malformados))[:5]}"
)

w["numero_vehiculos"] = pd.to_numeric(crudos_num.str.rstrip("."), errors="coerce").astype("Int64")

nulos_medida = int(w["numero_vehiculos"].isna().sum())
informadas_medida = int(w["numero_vehiculos"].notna().sum())
print(f"\nMedida cargada tal cual, sin imputar:")
print(f"   informada: {informadas_medida:,}")
print(f"   nula     : {nulos_medida:,} ({nulos_medida / len(w) * 100:.1f}%)")
print(f"   rango    : {w['numero_vehiculos'].min()} - {w['numero_vehiculos'].max()}")

Valores de 'Numero vehiculos' con formato anomalo: 5
   valores encontrados: '1.'

Medida cargada tal cual, sin imputar:
   informada: 176,577
   nula     : 194,421 (52.4%)
   rango    : 1 - 16

### T1c — Verificación de la reparación

Que el diccionario exista no garantiza que funcione. Aquí se comprueba, sobre
el resultado real del dataset y no sobre ejemplos de laboratorio, que:

1. La `Ñ` sobrevivió intacta (D2) y ninguna palabra quedó con el marcador.
2. No queda ni un solo `?` en los **catálogos controlados**.
3. Ninguna categoría quedó pegada por falta de espacios: si `NOAPLICA` y
   `NOQUIEREINTERVENCION` desaparecieron, el diccionario funcionó.
4. `direccion_reporte` sigue con `?`, y eso es deliberado.

#### Por que `direccion_reporte` queda fuera

`direccion_reporte` es **texto libre**: tiene decenas de miles de valores
distintos, y su mojibake afecta a palabras que un diccionario no puede
desambiguar. El `?` es la `Í` en `CL?NICA` y en `JARD?N`, pero es la `Ñ` en
`Ca?asgordas` (la calle Cañasgordas). Una regla global `?` -> `Í` arregla las
primeras y rompe la tercera.

Se normaliza el formato (mayusculas, espacios, acentos que si se pueden quitar
de forma segura) pero **no se adivina la letra que falta**. Es el mismo criterio
que se aplico antes con `Ca?da` vs `Da?os`: si no se puede saber con certeza,
no se inventa. Se reporta como limitacion conocida.

In [99]:
# --- D2: la ENE quedo intacta? ---------------------------------------------
ENE_ESPERADA = ["SOLO DAÑOS", "DAÑOS", "CAIDA DE OCUPANTE", "NO QUIERE INTERVENCION"]

catalogos_normalizados = {
    "tipo_confirmado": w["tipo_confirmado"],
    "detalle_confirmado": w["detalle_confirmado"],
    "tipo_accidente": w["tipo_accidente"],
    "medio_reporte": w["medio_reporte"],
}

print("D2 - categorias que exigen la ENE, y cuantas filas las tienen:")
for categoria in ENE_ESPERADA:
    total = sum(int((serie == categoria).sum()) for serie in catalogos_normalizados.values())
    print(f"   {categoria:<26s} {total:>8,d} filas")
    assert total > 0, f"'{categoria}' no aparece en ninguna columna: el diccionario no reparo"

_todas = set().union(*(set(s.dropna().unique()) for s in catalogos_normalizados.values()))
assert "DANOS" not in _todas, "'DANOS' (sin ENE) sigue presente: se perdio el cedillo"
assert "SOLO DANOS" not in _todas, "'SOLO DANOS' (sin ENE) presente: fallo la proteccion de la ENE"
print("   -> la ENE se conservo: 'DAÑOS' presente, 'DANOS' ausente")

FORMAS_PEGADAS = ["NOAPLICA", "NOQUIERE", "TELEFONICO1", "TELEF?NICO1"]

def _detectar_pegadas(categorias):
    """Devuelve las categorias que quedaron pegadas (sin espacios)."""
    halladas = []
    for categoria in categorias:
        if not isinstance(categoria, str):
            continue
        if categoria in ("NO APLICA", "NO QUIERE INTERVENCION", "TELEFONICO 127"):
            continue
        if any(categoria.startswith(p) for p in FORMAS_PEGADAS):
            halladas.append(categoria)
    return halladas

_proba = _detectar_pegadas(["NO QUIERE INTERVENCION", "NOQUIEREINTERVENCION",
                            "NO APLICA", "NOAPLICA", "TELEFONICO 127"])
assert "NOQUIEREINTERVENCION" in _proba, "El control no detecta la categoria pegada"
assert "NOAPLICA" in _proba, "El control no detecta 'NOAPLICA'"
assert "NO QUIERE INTERVENCION" not in _proba, "El control marca una forma correcta"
print(f"   -> control probado: detecta {len(_proba)} formas pegadas a proposito")
print(f"      {sorted(_proba)}")

pegadas = _detectar_pegadas(_todas)
assert not pegadas, (
    f"Categorias pegadas sin espacios que el diccionario no reparo: {pegadas}")
print("   -> sobre los datos reales: ninguna categoria pegada")

quedan = {nombre: int(serie.str.contains(r"\?", regex=True, na=False).sum())
          for nombre, serie in catalogos_normalizados.items()}
assert sum(quedan.values()) == 0, f"Quedaron '?' sin reparar: {quedan}"
print("   -> ningun '?' pendiente en los catalogos controlados")

con_interrogacion = int(w["direccion_reporte"].str.contains(r"\?", regex=True, na=False).sum())
print(f"\n   -> 'direccion_reporte' conserva '?' en {con_interrogacion:,} filas.")
print("      Es texto libre con decenas de miles de valores: el '?' puede ser la I de")
print("      'CL?NICA' o la ENE de 'Ca?asgordas'. No se adivina. Queda como limitacion.")

D2 - categorias que exigen la ENE, y cuantas filas las tienen:
   SOLO DAÑOS                  108,646 filas
   DAÑOS                             2 filas
   CAIDA DE OCUPANTE             1,476 filas
   NO QUIERE INTERVENCION       21,051 filas
   -> la ENE se conservo: 'DAÑOS' presente, 'DANOS' ausente
   -> control probado: detecta 2 formas pegadas a proposito
      ['NOAPLICA', 'NOQUIEREINTERVENCION']
   -> sobre los datos reales: ninguna categoria pegada
   -> ningun '?' pendiente en los catalogos controlados

   -> 'direccion_reporte' conserva '?' en 1,054 filas.
      Es texto libre con decenas de miles de valores: el '?' puede ser la I de
      'CL?NICA' o la ENE de 'Ca?asgordas'. No se adivina. Queda como limitacion.

### T1d — Variables derivadas (D7)

La Fase A solo pedía el texto de `tipos_vehiculos`. De ahí salen cinco columnas
nuevas que hacen consultable la dimensión sin volver a partir cadenas:

| Columna | Origen | Para qué sirve |
|---|---|---|
| `num_tipos_vehiculos` | conteo de tokens | amplitud de la combinación |
| `involucra_motocicleta` | lista explícita | por que importa: las motos son el grupo de riesgo |
| `involucra_mototriciclo` | lista explícita | categoría mayoritaria de la fuente |
| `dia_semana` | `dim_fecha` | distinguir dia laborable de fin de semana |
| `es_fin_de_semana` | `dim_fecha` | bandera booleana equivalente |

#### Por qué el conteo de tokens y no el conteo de tipos distintos

`AUTOMOVIL, AUTOMOVIL` son **dos vehículos** y es información válida. Por eso
`num_tipos_vehiculos` cuenta tokens con repetición, no valores únicos. La
combinación canónica sigue llevando sus repetidos, que es justamente lo que
permite recuperar ese conteo desde la dimensión.

#### Por qué dos banderas y no una

La fuente mezcla moto de dos ruedas (`MOTOCICLETA`, `MOTOCICLO`,
`CICLOMOTOR`) con triciclos motorizados (`MOTOCARRO`, `MOTOTRICICLO`,
`TRICIMOTO`, `CUATRIMOTO`). Tratarlos como la misma categoría mezcla dos
fenómenos distintos, y el segundo es además el más frecuente en la fuente. Son
**dos banderas independientes y no excluyentes**: hay combinaciones con ambas.

In [100]:
# --- D7: las dos banderas de vehiculos -------------------------------------
LISTA_MOTOCICLETAS = {"MOTOCICLETA", "MOTOCICLO", "CICLOMOTOR"}
LISTA_MOTOTRICICLOS = {"MOTOCARRO", "MOTOTRICICLO", "TRICIMOTO", "CUATRIMOTO"}

In [101]:
# --- Conteo de tokens reales, excluyendo las etiquetas centinela ------------
_sin_vehiculos = w["tipos_vehiculos"].isin(ETIQUETAS_CENTINELA_VEHICULOS)
combinaciones_reales = w.loc[~_sin_vehiculos, "tipos_vehiculos"].dropna()

print(f"Reparticion de los {len(w):,} reportes segun lo que declaran sus vehiculos:")
print(f"   combinacion real de vehiculos ................. {len(combinaciones_reales):,}")
print(f"   '{ETIQUETA_SIN_ACCIDENTE}' (no hubo accidente) . "
      f"{int((w['tipos_vehiculos'] == ETIQUETA_SIN_ACCIDENTE).sum()):,}")
print(f"   '{NOMBRE_DESCONOCIDO}' (no informado, id -1) .... "
      f"{int(w['tipos_vehiculos'].isna().sum()):,}")
assert len(combinaciones_reales) + int((w["tipos_vehiculos"] == ETIQUETA_SIN_ACCIDENTE).sum()) \
    + int(w["tipos_vehiculos"].isna().sum()) == len(w), "La particion de vehiculos no cuadra"

serie_tokens = combinaciones_reales.str.split(", ").explode()
frecuencia_tokens = serie_tokens.value_counts()
print(f"\nTokens distintos en combinaciones reales: {int(serie_tokens.nunique()):,}")
print(f"Frecuencia de cada token (las {len(frecuencia_tokens)} categorias):")
print(frecuencia_tokens.to_string())

Reparticion de los 370,998 reportes segun lo que declaran sus vehiculos:
   combinacion real de vehiculos ................. 148,780
   'SIN ACCIDENTE (NEGATIVO)' (no hubo accidente) . 199,031
   'DESCONOCIDO' (no informado, id -1) .... 23,187

Tokens distintos en combinaciones reales: 50
Frecuencia de cada token (las 50 categorias):
tipos_vehiculos
AUTOMOVIL                155914
MOTOCICLETA               77030
CAMIONETA                 13352
CAMION                     7755
BUSETA                     4192
BUS PADRON                 3186
BUS                        3174
CAMPERO                    2672
VOLQUETA                   1837
BUS ARTICULADO             1500
BUS ALIMENTADOR            1419
BICICLETA                  1321
AMBULANCIA                  842
TRACTO/CAMION               767
MICROBUS                    599
MOTOCARRO                   468
GRUA                        374
VAN                         308
AUTOMOVIL TURISMO           288
MOTOCICLO                   133
CAMION CISTERNA              78
APLANADORA                   53
MINI VAN                     43
COMPACTADORA                 26
TRACTOCAMION                 24
CAMION CARGA EXTENSA         23
BARREDORA                    20
MINIBUS                      17
MOTOTRICICLO                 16
MAQUINARIA INDUSTRIAL        11
TRACCION ANIMAL               9
MINICARGADOR                  8
AMBULANCIA CAMPERO            7
EXCAVADORA                    5
TRICIMOTO                     5
CARRETILLA ELEVADORA          4
CUATRIMOTO                    4
CARGADORA FRONTAL             4
REMOLQUE                      3
TRITURADORA                   3
MAQ. AGRICOLA                 3
ABONADORA                     2
PRENSA HIDRAULICA             2
SEMIREMOLQUE                  2
BUSPADRON                     2
AUTOMOVILTURISMO              1
TRACTOR                       1
CORTADORA                     1
MAQ. INDUSTRIAL               1
CICLOMOTOR                    1

In [102]:
# --- Tokens con 'MOTO': listado completo, para revisar el criterio ---------
TOKENS_MOTO = ["MOTOCICLETA", "MOTOCICLO", "MOTOCARRO", "MOTOTRICICLO",
               "TRICIMOTO", "CUATRIMOTO", "CICLOMOTOR"]

vehiculos_planos = w["tipos_vehiculos"].dropna().str.split(", ")
serie_tokens = vehiculos_planos.explode()
frecuencia_tokens = serie_tokens.value_counts()

print("Todos los tokens que contienen 'MOTO', con su frecuencia:")
tabla_moto = frecuencia_tokens[frecuencia_tokens.index.str.contains("MOTO")]
print(tabla_moto.to_string())

sin_cubrir = [t for t in tabla_moto.index if t not in TOKENS_MOTO]
assert not sin_cubrir, (
    f"Tokens con 'MOTO' no cubiertos por las listas declaradas: {sin_cubrir}. "
    "Revisar si deben entrar en alguna bandera."
)
print(f"\n   -> los {len(tabla_moto)} tokens con 'MOTO' estan cubiertos por las listas")

Todos los tokens que contienen 'MOTO', con su frecuencia:
tipos_vehiculos
MOTOCICLETA     77030
MOTOCARRO         468
MOTOCICLO         133
MOTOTRICICLO       16
TRICIMOTO           5
CUATRIMOTO          4
CICLOMOTOR          1

   -> los 7 tokens con 'MOTO' estan cubiertos por las listas

In [103]:
# --- D7: las dos banderas, pesadas por filas del hecho ---------------------
_por_combinacion = combinaciones_reales.drop_duplicates().to_frame("tipos_vehiculos")
_por_combinacion = _por_combinacion.assign(
    n_tokens=_por_combinacion["tipos_vehiculos"].str.count(",").add(1),
    filas=_por_combinacion["tipos_vehiculos"].map(combinaciones_reales.value_counts()),
)
_por_combinacion["moto"] = _por_combinacion["tipos_vehiculos"].map(
    lambda v: bool(LISTA_MOTOCICLETAS & set(v.split(", "))))
_por_combinacion["triciclo"] = _por_combinacion["tipos_vehiculos"].map(
    lambda v: bool(LISTA_MOTOTRICICLOS & set(v.split(", "))))

_reporte = pd.DataFrame({
    "combinaciones": [len(_por_combinacion)],
    "con ambas banderas": [int((_por_combinacion["moto"] & _por_combinacion["triciclo"]).sum())],
    "con al menos una": [int((_por_combinacion["moto"] | _por_combinacion["triciclo"]).sum())],
    "con ninguna": [int((~_por_combinacion["moto"] & ~_por_combinacion["triciclo"]).sum())],
}).T.rename(columns={0: "combinaciones"})

_ambos_filas = int(combinaciones_reales.isin(
    _por_combinacion.loc[_por_combinacion["moto"] & _por_combinacion["triciclo"],
                         "tipos_vehiculos"]).sum())
_alguna_filas = int(combinaciones_reales.isin(
    _por_combinacion.loc[_por_combinacion["moto"] | _por_combinacion["triciclo"],
                         "tipos_vehiculos"]).sum())
_n_sin_vehiculo = len(w) - len(combinaciones_reales)

print("D7 - las dos banderas, al nivel de la combinacion real:")
print(_reporte.to_string())
print("\nD7 - las mismas banderas, pesadas por filas del hecho:")
print(f"   ambas banderas ........................ {_ambos_filas:,} filas")
print(f"   al menos una ......................... {_alguna_filas:,} filas")
print(f"   ninguna, con combinacion informada ... "
      f"{len(combinaciones_reales) - _alguna_filas:,} filas")
print(f"   sin ningun vehiculo declarado ........ {_n_sin_vehiculo:,} filas "
      f"({ETIQUETA_SIN_ACCIDENTE} + {NOMBRE_DESCONOCIDO})")
assert _ambos_filas > 0, "Se esperaba alguna combinacion con ambas banderas"

print("\nDistribucion del numero de tokens por combinacion (con repetidos):")
print(_por_combinacion["n_tokens"].value_counts().sort_index().to_string())

print("\nLas 10 combinaciones mas frecuentes, con sus banderas:")
print(_por_combinacion.nlargest(10, "filas")[
    ["tipos_vehiculos", "n_tokens", "moto", "triciclo", "filas"]
].to_string(index=False))

D7 - las dos banderas, al nivel de la combinacion real:
                    combinaciones
combinaciones                 733
con ambas banderas             11
con al menos una              273
con ninguna                   460

D7 - las mismas banderas, pesadas por filas del hecho:
   ambas banderas ........................ 127 filas
   al menos una ......................... 68,238 filas
   ninguna, con combinacion informada ... 80,542 filas
   sin ningun vehiculo declarado ........ 222,218 filas (SIN ACCIDENTE (NEGATIVO) + DESCONOCIDO)

Distribucion del numero de tokens por combinacion (con repetidos):
n_tokens
1     35
2    272
3    255
4    121
5     48
7      2

Las 10 combinaciones mas frecuentes, con sus banderas:
                tipos_vehiculos  n_tokens  moto  triciclo  filas
           AUTOMOVIL, AUTOMOVIL         2 False     False  38831
         AUTOMOVIL, MOTOCICLETA         2  True     False  35183
                    MOTOCICLETA         1  True     False  13506
                      AUTOMOVIL         1 False     False   9618
       MOTOCICLETA, MOTOCICLETA         2  True     False   7865
           AUTOMOVIL, CAMIONETA         2 False     False   4984
              AUTOMOVIL, CAMION         2 False     False   3893
         CAMIONETA, MOTOCICLETA         2  True     False   2997
AUTOMOVIL, AUTOMOVIL, AUTOMOVIL         3 False     False   2121
              AUTOMOVIL, BUSETA         2 False     False   1900

In [104]:
# --- D7: variables de la dimension fecha ----------------------------------
w["anio"] = w["fecha"].dt.year.astype("Int64")
w["mes"] = w["fecha"].dt.month.astype("Int64")
w["trimestre"] = w["fecha"].dt.quarter.astype("Int64")
w["dia_semana"] = w["fecha"].dt.day_name()
w["es_fin_de_semana"] = w["fecha"].dt.dayofweek >= 5
w["dia_del_anio"] = w["fecha"].dt.dayofyear.astype("Int64")

print("Dia de la semana (nombre en ingles, el de la libreria):")
print(w["dia_semana"].value_counts().to_string())
print(f"\nFechas sin dia de semana: {int(w['dia_semana'].isna().sum()):,}")
assert w["dia_semana"].notna().all(), "Hay fechas sin dia de semana: revisar el parseo"
print("\nValidacion D7 (fecha): OK")

Dia de la semana (nombre en ingles, el de la libreria):
dia_semana
Friday       58673
Tuesday      56283
Saturday     55358
Thursday     55158
Wednesday    54906
Monday       51253
Sunday       39367

Fechas sin dia de semana: 0

Validacion D7 (fecha): OK

### T1e — Construcción de las dimensiones y del hecho

Con `w` normalizado, se arma el modelo estrella. El procedimiento es el mismo
para todas las dimensiones y se apoya en dos funciones:

| Función | Qué hace |
|---|---|
| `construir_dim` | numeración `1, 2, 3…` de los valores distintos + la fila `-1` |
| `mapear_centinela` | traduce los nulos a la clave `-1` de esa dimensión |

#### La decisión de fondo: las dimensiones son de 1 en 1

Cada valor distinto recibe un id correlativo, **sin ordenar por nombre ni por
frecuencia**. El id es una etiqueta, no un orden de negocio. Y el hecho
**reutiliza el mismo id** en vez de crear una copia: una tabla de 370 mil filas
no duplica seis dimensiones.

`id = -1` es siempre la fila `DESCONOCIDO` de la dimensión, y existe aunque
nunca se use. `numero_vehiculos` no es dimensión: es la única medida, y por eso
va en el hecho y no en ninguna tabla aparte.

In [105]:
# --- Funciones de construccion del modelo estrella --------------------------
# 'dim_tipo_confirmado' usa dos columnas: el par (tipo, detalle).
DIMENSIONES = {}
CLAVES_DIM = {}      # nombre de la tabla -> columnas de negocio que la identifican

def construir_dim(nombre, columnas_valor):
    """Construye una dimension con id 1..n y, al final, la fila id = -1.

    El id se asigna en orden de aparicion de los valores distintos, no
    alfabeticamente: el id es una etiqueta tecnica, no un orden de negocio.
    """
    valores = w[columnas_valor]
    distintos = valores.dropna().drop_duplicates().reset_index(drop=True)

    id_col = "id_" + nombre.split("_", 1)[1]
    dim = distintos.copy()
    dim.insert(0, id_col, range(1, len(dim) + 1))
    for columna in columnas_valor:
        if dim[columna].dtype == "object":
            dim[columna] = dim[columna].astype("string")

    centinela = {id_col: -1}
    centinela.update({c: NOMBRE_DESCONOCIDO for c in columnas_valor})
    if len(dim):
        dim = pd.concat([dim, pd.DataFrame([centinela])], ignore_index=True)

    DIMENSIONES[nombre] = dim
    CLAVES_DIM[nombre] = columnas_valor
    return dim

def mapear_centinela(nombre_dim):
    """Columna de claves FK del hecho: id real, o -1 si el valor es nulo.

    El merge es sobre las columnas de negocio de la dimension y devuelve -1
    para lo que no encontro, que es exactamente el caso 'el dato es nulo'.
    """
    dim = DIMENSIONES[nombre_dim]
    id_col = dim.columns[0]
    columnas = CLAVES_DIM[nombre_dim]
    reales = dim[dim[id_col] != -1][[id_col] + columnas]
    fusion = w[columnas].merge(reales, on=columnas, how="left")
    return fusion[id_col].fillna(-1).astype("int64").to_numpy()

# --- dim_fecha: la clave es la fecha ----------------------------------------
MESES_ES = ["ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO",
            "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"]
DIAS_ES = ["LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO"]

dim_fecha = pd.DataFrame({"fecha": sorted(w["fecha"].dropna().unique())})
dim_fecha.insert(0, "id_fecha", range(1, len(dim_fecha) + 1))
dim_fecha["anio"] = dim_fecha["fecha"].dt.year.astype("Int64")
dim_fecha["mes"] = dim_fecha["fecha"].dt.month.astype("Int64")
dim_fecha["nombre_mes"] = dim_fecha["mes"].map(lambda m: MESES_ES[int(m) - 1])
dim_fecha["trimestre"] = dim_fecha["fecha"].dt.quarter.astype("Int64")
dim_fecha["dia_del_anio"] = dim_fecha["fecha"].dt.dayofyear.astype("Int64")
dim_fecha["dia_semana"] = dim_fecha["fecha"].dt.dayofweek.map(lambda d: DIAS_ES[d])
dim_fecha["dia_semana_num"] = dim_fecha["fecha"].dt.dayofweek.astype("Int64") + 1
dim_fecha["es_fin_de_semana"] = dim_fecha["fecha"].dt.dayofweek >= 5

dim_fecha = pd.concat(
    [dim_fecha, pd.DataFrame([{
        "id_fecha": -1, "fecha": pd.NaT, "anio": pd.NA, "mes": pd.NA,
        "nombre_mes": NOMBRE_DESCONOCIDO, "trimestre": pd.NA,
        "dia_del_anio": pd.NA, "dia_semana": NOMBRE_DESCONOCIDO,
        "dia_semana_num": pd.NA, "es_fin_de_semana": pd.NA,
    }])],
    ignore_index=True,
)
for columna in ["anio", "mes", "trimestre", "dia_del_anio", "dia_semana_num"]:
    dim_fecha[columna] = dim_fecha[columna].astype("Int64")
dim_fecha["es_fin_de_semana"] = dim_fecha["es_fin_de_semana"].astype("boolean")
dim_fecha["fecha"] = pd.to_datetime(dim_fecha["fecha"])
DIMENSIONES["dim_fecha"] = dim_fecha
CLAVES_DIM["dim_fecha"] = ["fecha"]

# --- Las cinco dimensiones de texto -----------------------------------------
dim_ubicacion = construir_dim("dim_ubicacion", ["direccion_reporte"])
dim_tipo_accidente = construir_dim("dim_tipo_accidente", ["tipo_accidente"])
dim_medio_reporte = construir_dim("dim_medio_reporte", ["medio_reporte"])

dim_tipo_confirmado = construir_dim(
    "dim_tipo_confirmado", ["tipo_confirmado", "detalle_confirmado"])

# --- dim_vehiculos: la combinacion canonica + las 3 columnas de D7 ----------
dim_vehiculos = construir_dim("dim_vehiculos_implicados", ["tipos_vehiculos"])

def _tokens_de(valor):
    """Tokens de una combinacion, o None si la fila no declara vehiculos."""
    if pd.isna(valor) or valor in ETIQUETAS_CENTINELA_VEHICULOS:
        return None
    return valor.split(", ")

def _n_de_tokens(valor):
    tokens = _tokens_de(valor)
    return pd.NA if tokens is None else len(tokens)

def _involucra(valor, lista):
    tokens = _tokens_de(valor)
    return pd.NA if tokens is None else bool(lista & set(tokens))

dim_vehiculos["num_tipos_vehiculos"] = dim_vehiculos["tipos_vehiculos"].map(
    _n_de_tokens).astype("Int64")
dim_vehiculos["involucra_motocicleta"] = dim_vehiculos["tipos_vehiculos"].map(
    lambda v: _involucra(v, LISTA_MOTOCICLETAS)).astype("boolean")
dim_vehiculos["involucra_mototriciclo"] = dim_vehiculos["tipos_vehiculos"].map(
    lambda v: _involucra(v, LISTA_MOTOTRICICLOS)).astype("boolean")

for columna in ["num_tipos_vehiculos", "involucra_motocicleta", "involucra_mototriciclo"]:
    sin_vehiculo = dim_vehiculos["tipos_vehiculos"].isin(ETIQUETAS_CENTINELA_VEHICULOS)
    assert dim_vehiculos.loc[sin_vehiculo, columna].isna().all(), (
        f"'{columna}' tiene valor en una fila que no declara vehiculos: "
        f"{dim_vehiculos.loc[sin_vehiculo, columna].dropna().unique().tolist()}"
    )
print("K3 - atributos de vehiculo nulos en las filas sin vehiculo: OK")
for etiqueta in sorted(ETIQUETAS_CENTINELA_VEHICULOS):
    fila = dim_vehiculos.loc[dim_vehiculos["tipos_vehiculos"] == etiqueta]
    if len(fila):
        print(f"   {etiqueta:<26s} num_tipos_vehiculos = "
              f"{fila['num_tipos_vehiculos'].iloc[0]}  (NULL, no 1)")

K3 - atributos de vehiculo nulos en las filas sin vehiculo: OK
   DESCONOCIDO                num_tipos_vehiculos = <NA>  (NULL, no 1)
   SIN ACCIDENTE (NEGATIVO)   num_tipos_vehiculos = <NA>  (NULL, no 1)

In [106]:
# --- Coherencia entre la medida y la combinacion declarada ------------------
# 'numero_vehiculos' y 'num_tipos_vehiculos' cuentan cosas distintas.
_comparable = combinaciones_reales.notna() & w["numero_vehiculos"].notna()
_num_tipos = combinaciones_reales.map(
    lambda v: len(v.split(", ")) if pd.notna(v) else pd.NA).astype("Int64")
_diferencia = (w["numero_vehiculos"][_comparable].astype("int64")
               - _num_tipos[_comparable].astype("int64"))

_coinciden = int((_diferencia == 0).sum())
_difieren = int((_diferencia != 0).sum())
print(f"Coherencia 'numero_vehiculos' vs 'num_tipos_vehiculos' "
      f"(solo combinaciones reales con la medida informada):")
print(f"   filas comparables: {int(_comparable.sum()):,}")
print(f"   coinciden        : {_coinciden:,} "
      f"({_coinciden / int(_comparable.sum()) * 100:.1f}%)")
print(f"   difieren         : {_difieren:,} "
      f"({_difieren / int(_comparable.sum()) * 100:.1f}%)")
print("\n   diferencia = numero_vehiculos - num_tipos_vehiculos:")
_tabla_dif = _diferencia.value_counts().sort_index()
_tabla_dif.index.name = "diferencia"
_tabla_dif.name = "filas"
print(_tabla_dif.head(8).to_string())

_subinformada = int((_diferencia > 0).sum())
_sobreinformada = int((_diferencia < 0).sum())
print(f"\n   la lista menciona MENOS vehiculos de los que informa la medida: "
      f"{_subinformada:,} filas")
print(f"   la lista menciona MAS vehiculos que la medida .................: "
      f"{_sobreinformada:,} filas")
print("   -> se documenta, NO se corrige: no hay informacion para saber cuantos")
print("      vehiculos declarados. Para analisis, use 'numero_vehiculos'.")

Coherencia 'numero_vehiculos' vs 'num_tipos_vehiculos' (solo combinaciones reales con la medida informada):
   filas comparables: 148,671
   coinciden        : 134,014 (90.1%)
   difieren         : 14,657 (9.9%)

   diferencia = numero_vehiculos - num_tipos_vehiculos:
diferencia
-4         1
-1         2
 0    134014
 1     14413
 2       214
 3        16
 4        10
 6         1

   la lista menciona MENOS vehiculos de los que informa la medida: 14,654 filas
   la lista menciona MAS vehiculos que la medida .................: 3 filas
   -> se documenta, NO se corrige: no hay informacion para saber cuantos
      vehiculos declarados. Para analisis, use 'numero_vehiculos'.

In [107]:
# --- El hecho ---------------------------------------------------------------
HECHO = pd.DataFrame({
    "id_siniestro": range(1, len(w) + 1),
    "codigo_reporte": w["codigo_reporte"],
    "id_fecha": mapear_centinela("dim_fecha"),
    "id_ubicacion": mapear_centinela("dim_ubicacion"),
    "id_tipo_accidente": mapear_centinela("dim_tipo_accidente"),
    "id_tipo_confirmado": mapear_centinela("dim_tipo_confirmado"),
    "id_medio_reporte": mapear_centinela("dim_medio_reporte"),
    "id_vehiculos_implicados": mapear_centinela("dim_vehiculos_implicados"),
    "numero_vehiculos": w["numero_vehiculos"].astype("Int64"),
})

print(f"Tabla de hechos: {len(HECHO):,} filas x {HECHO.shape[1]} columnas")
print("\nLas siete tablas del modelo:")
for nombre, tabla in [("hecho_siniestralidad", HECHO)] + list(DIMENSIONES.items()):
    print(f"   {nombre:<28s} {len(tabla):>7,d} filas  {tabla.shape[1]:>2d} columnas")

Tabla de hechos: 370,998 filas x 9 columnas

Las siete tablas del modelo:
   hecho_siniestralidad         370,998 filas   9 columnas
   dim_fecha                      3,230 filas  10 columnas
   dim_ubicacion                 59,349 filas   2 columnas
   dim_tipo_accidente                10 filas   2 columnas
   dim_medio_reporte                 11 filas   2 columnas
   dim_tipo_confirmado               38 filas   3 columnas
   dim_vehiculos_implicados         735 filas   5 columnas

### T1f — Control de calidad antes de cargar

Un ETL que no falla no significa que esté bien. Estas comprobaciones son
**duras**: si algo no cuadra, la ejecución se detiene con un `AssertionError` en
lugar de subir datos silenciosamente corruptos.

Se valida lo que suele romperse en un modelo estrella:

1. **Integridad referencial** — todo id del hecho existe en su dimensión.
2. **Reconciliación de nulos** — el número de filas con `id = -1` debe
   coincidir exactamente con el número de valores nulos de origen. Es la
   comprobación que detecta una fuga: si un nulo se perdió en el camino, los
   dos números dejan de cuadrar.
3. **Grano de la tabla** — el código de reporte es único y las PK no se repiten.
4. **La marca `DESCONOCIDO`** — existe una sola vez y solo en la fila `-1`.
5. **Valores de la enumeración** — las banderas booleanas solo tienen `True`,
   `False` o nulo.

In [108]:
# --- D5: reconciliacion de las claves foraneas -----------------------------
_negativo_crudo = normalizar_texto(df["Tipo confirmado"]).eq("NEGATIVO")
_ta_crudo = normalizar_texto(df["Tipo clase de accidente"])
_veh_crudo = df["Tipo de vehículos implicados"]

_nulo_tipo = int(_ta_crudo.isna().sum())
_neg_con_tipo_nulo = int((_ta_crudo.isna() & _negativo_crudo).sum())
_esperado_tipo_accidente = _nulo_tipo - _neg_con_tipo_nulo

_sin_token_valido = int(_veh_crudo.map(_canonizar_vehiculos).isna().sum())
_neg_sin_token = int((_veh_crudo.map(_canonizar_vehiculos).isna() & _negativo_crudo).sum())
_esperado_vehiculos = _sin_token_valido - _neg_sin_token

_negativo_crudo = _negativo_crudo.fillna(False)

print("D5 - aritmetica del esperado, calculada sobre el CSV CRUDO")
print(f"\n  id_tipo_accidente = -1")
print(f"     nulos crudos en 'Tipo clase de accidente' ........... {_nulo_tipo:>8,d}")
print(f"     menos reportes NEGATIVO (van a SIN ACCIDENTE) ........ {_neg_con_tipo_nulo:>8,d}")
print(f"     = esperado .......................................... {_esperado_tipo_accidente:>8,d}")
print(f"\n  id_vehiculos_implicados = -1")
print(f"     celdas sin ningun token valido en la fuente .......... {_sin_token_valido:>8,d}")
print(f"     menos reportes NEGATIVO (van a SIN ACCIDENTE) ........ {_neg_sin_token:>8,d}")
print(f"     = esperado .......................................... {_esperado_vehiculos:>8,d}")

print("\n  Aritmetica explicada de 'sin ningun token valido':")
_vacias = int(_veh_crudo.isna().sum())
_informadas_sin_token = _sin_token_valido - _vacias
print(f"     celda vacia en la fuente ........................... {_vacias:>8,d}")
print(f"     celda informada sin ningun tipo valido (C4) ........ {_informadas_sin_token:>8,d}")
print(f"     = total ............................................ {_sin_token_valido:>8,d}")

CONTROLES_RECONCILIACION = [
    ("id_fecha", "dim_fecha", 0,
     "toda fecha del CSV se parsea"),
    ("id_ubicacion", "dim_ubicacion", int(normalizar_texto(df["Dirección reporte"]).isna().sum()),
     "nulos crudos de 'Direccion reporte'"),
    ("id_tipo_accidente", "dim_tipo_accidente", _esperado_tipo_accidente,
     "nulos de tipo de accidente MINUS los NEGATIVO"),
    ("id_tipo_confirmado", "dim_tipo_confirmado",
     int(normalizar_texto(df["Tipo confirmado"]).isna().sum()),
     "nulos crudos de 'Tipo confirmado'"),
    ("id_medio_reporte", "dim_medio_reporte",
     int(normalizar_texto(df["Medio de reporte"]).isna().sum()),
     "nulos crudos de 'Medio de reporte'"),
    ("id_vehiculos_implicados", "dim_vehiculos_implicados", _esperado_vehiculos,
     "celdas sin token valido MINUS las NEGATIVO"),
]

filas_reconciliacion = []
for columna, dim_nombre, esperado, motivo in CONTROLES_RECONCILIACION:
    en_hecho = int((HECHO[columna] == -1).sum())
    filas_reconciliacion.append({
        "columna": columna,
        "origen": f"-1 ({motivo})",
        "en_hecho": en_hecho,
        "esperado": esperado,
        "ok": "OK" if en_hecho == esperado else "DESCUADRE",
    })
    assert en_hecho == esperado, (
        f"Reconciliacion fallida en '{columna}': el hecho tiene {en_hecho} filas con "
        f"id = -1 y el esperado calculado desde el CSV crudo es {esperado} "
        f"({motivo}). Se perdio o se invento informacion."
    )

print("\nD5 - reconciliacion de claves foraneas (id = -1):")
print(pd.DataFrame(filas_reconciliacion).to_string(index=False))
print("\n   -> todas las columnas cuadran contra el crudo, no contra 'w'")

_otro_esperado = int(es_narrativa.sum()) + n_otro_fuente_solo
_otro_real = int((w["medio_reporte"] == ETIQUETA_OTRO).sum())
print(f"\nD3 - filas en '{ETIQUETA_OTRO}': {_otro_real:,} "
      f"= {int(es_narrativa.sum()):,} narrativas anonimizadas + "
      f"{n_otro_fuente_solo:,} 'OTRO'/'OTRO VALOR' de la fuente "
      f"({n_otro_fuente_y_narrativa} de estas ya venian de la fuente)")
assert _otro_real == _otro_esperado, (
    f"'OTRO' tiene {_otro_real} filas y se esperaban {_otro_esperado} "
    f"({int(es_narrativa.sum())} narrativas + {n_otro_fuente} 'OTRO VALOR')."
)
print("   -> cuadra: ninguna otra fila entra en 'OTRO'")

D5 - aritmetica del esperado, calculada sobre el CSV CRUDO

  id_tipo_accidente = -1
     nulos crudos en 'Tipo clase de accidente' ...........  325,253
     menos reportes NEGATIVO (van a SIN ACCIDENTE) ........  227,937
     = esperado ..........................................   97,316

  id_vehiculos_implicados = -1
     celdas sin ningun token valido en la fuente ..........  222,218
     menos reportes NEGATIVO (van a SIN ACCIDENTE) ........  199,031
     = esperado ..........................................   23,187

  Aritmetica explicada de 'sin ningun token valido':
     celda vacia en la fuente ...........................  222,210
     celda informada sin ningun tipo valido (C4) ........        8
     = total ............................................  222,218

D5 - reconciliacion de claves foraneas (id = -1):
                columna                                             origen  en_hecho  esperado ok
               id_fecha                  -1 (toda fecha del CSV se parsea)         0         0 OK
           id_ubicacion           -1 (nulos crudos de 'Direccion reporte')    183681    183681 OK
      id_tipo_accidente -1 (nulos de tipo de accidente MINUS los NEGATIVO)     97316     97316 OK
     id_tipo_confirmado             -1 (nulos crudos de 'Tipo confirmado')         2         2 OK
       id_medio_reporte            -1 (nulos crudos de 'Medio de reporte')    288094    288094 OK
id_vehiculos_implicados    -1 (celdas sin token valido MINUS las NEGATIVO)     23187     23187 OK

   -> todas las columnas cuadran contra el crudo, no contra 'w'

D3 - filas en 'OTRO': 14 = 5 narrativas anonimizadas + 9 'OTRO'/'OTRO VALOR' de la fuente (0 de estas ya venian de la fuente)
   -> cuadra: ninguna otra fila entra en 'OTRO'

In [109]:
# --- Integridad referencial, unicidad y enumeraciones ----------------------
TABLAS = {"hecho_siniestralidad": HECHO, **DIMENSIONES}
PK = {
    "hecho_siniestralidad": "id_siniestro", "dim_fecha": "id_fecha",
    "dim_ubicacion": "id_ubicacion", "dim_tipo_accidente": "id_tipo_accidente",
    "dim_tipo_confirmado": "id_tipo_confirmado",
    "dim_medio_reporte": "id_medio_reporte",
    "dim_vehiculos_implicados": "id_vehiculos_implicados",
}

for nombre, tabla in TABLAS.items():
    clave = PK[nombre]
    assert tabla[clave].is_unique, f"PK '{clave}' de {nombre} tiene valores repetidos"
    assert not tabla[clave].isna().any(), f"PK '{clave}' de {nombre} tiene nulos"
print("1) Claves primarias unicas y sin nulos en las 7 tablas: OK")

for columna, dim_nombre, _, _ in CONTROLES_RECONCILIACION:
    id_col = DIMENSIONES[dim_nombre].columns[0]
    validos = set(DIMENSIONES[dim_nombre][id_col])
    huerfanas = int((~HECHO[columna].isin(validos)).sum())
    assert huerfanas == 0, f"{columna} tiene {huerfanas} ids que no existen en {dim_nombre}"
print("2) Integridad referencial: no hay ids huerfanos en ninguna FK: OK")

resumen_centinelas = []
for nombre in DIMENSIONES:
    tabla = DIMENSIONES[nombre]
    clave = tabla.columns[0]
    n_desconocido = int((tabla[clave] == -1).sum())
    resumen_centinelas.append({"dimension": nombre, "filas": len(tabla),
                               "filas_id_menos_1": n_desconocido})
for fila in resumen_centinelas:
    dim_nombre = fila["dimension"]
    assert fila["filas_id_menos_1"] <= 1, (
        f"{dim_nombre} tiene {fila['filas_id_menos_1']} filas con id = -1")
    if fila["filas_id_menos_1"] == 1:
        tabla = DIMENSIONES[dim_nombre]
        clave = tabla.columns[0]
        columna_valor = CLAVES_DIM[dim_nombre][0]
        assert columna_valor in tabla.columns, (
            f"{dim_nombre} no tiene la columna de valor '{columna_valor}'. "
            f"Tiene: {tabla.columns.tolist()}")
        centinela = tabla.loc[tabla[clave] == -1, columna_valor].iloc[0]
        if dim_nombre == "dim_fecha":
            assert pd.isna(centinela), (
                f"La fila -1 de {dim_nombre} deberia tener fecha NULL, "
                f"pero tiene {centinela!r}")
            for columna in ("nombre_mes", "dia_semana"):
                if columna not in tabla.columns:
                    continue
                assert tabla.loc[tabla[clave] == -1, columna].iloc[0] \
                    == NOMBRE_DESCONOCIDO, (
                    f"La fila -1 de {dim_nombre} no dice {chr(39)}DESCONOCIDO{chr(39)} "
                    f"en '{columna}'")
                assert not tabla.loc[tabla[clave] != -1, columna] \
                    .eq(NOMBRE_DESCONOCIDO).any(), (
                    f"{dim_nombre} tiene filas reales con DESCONOCIDO "
                    f"en '{columna}'")
        else:
            assert centinela == NOMBRE_DESCONOCIDO, (
                f"La fila -1 de {dim_nombre} no dice {chr(39)}DESCONOCIDO{chr(39)} "
                f"en '{columna_valor}': dice {centinela!r}")
            reales = tabla[tabla[clave] != -1]
            assert not reales[columna_valor].eq(NOMBRE_DESCONOCIDO).any(), (
                f"{dim_nombre} tiene filas reales con el valor "
                f"'{NOMBRE_DESCONOCIDO}'")
print("3) Cada dimension tiene a lo sumo una fila -1, y dice DESCONOCIDO solo ahi:")
print(pd.DataFrame(resumen_centinelas).to_string(index=False))

for columna in ["involucra_motocicleta", "involucra_mototriciclo"]:
    valores = set(dim_vehiculos[columna].dropna().unique())
    assert valores <= {True, False}, f"{columna} tiene valores fuera de {{True, False}}: {valores}"
print("4) Las banderas booleanas solo contienen True / False / nulo: OK")

1) Claves primarias unicas y sin nulos en las 7 tablas: OK
2) Integridad referencial: no hay ids huerfanos en ninguna FK: OK
3) Cada dimension tiene a lo sumo una fila -1, y dice DESCONOCIDO solo ahi:
               dimension  filas  filas_id_menos_1
               dim_fecha   3230                 1
           dim_ubicacion  59349                 1
      dim_tipo_accidente     10                 1
       dim_medio_reporte     11                 1
     dim_tipo_confirmado     38                 1
dim_vehiculos_implicados    735                 1
4) Las banderas booleanas solo contienen True / False / nulo: OK

### T1g — D4: ¿son comparables los años?

Antes de cargar conviene mirar si el periodo 2016–2024 es homogéneo. Si un año
está a medio camino, cualquier comparación de volumen anual entre ese año y los
demás va a subestimarlo, y eso hay que documentarlo **antes** de que la Fase C
saque conclusiones.

El rango real de fechas se calcula aquí, no se escribe a mano.

In [110]:
# --- D4: cobertura temporal real -------------------------------------------
FECHA_MAX = pd.Timestamp(w["fecha"].max())
RANGO = {
    "inicio": w["fecha"].min().date(),
    "fin": FECHA_MAX.date(),
    "filas": len(w),
}

_por_anio = w.groupby("anio").agg(
    reportes=("codigo_reporte", "size"),
    con_vehiculos=("numero_vehiculos", lambda s: s.notna().sum()),
    primero=("fecha", "min"),
    ultimo=("fecha", "max"),
).reset_index()

_por_anio["dias_covered"] = (
    (_por_anio["ultimo"] - _por_anio["primero"]).dt.days + 1)
_por_anio["reportes por dia cubierto"] = (
    _por_anio["reportes"] / _por_anio["dias_covered"]).round(1)
_por_anio["% con numero_vehiculos"] = (
    _por_anio["con_vehiculos"] / _por_anio["reportes"] * 100).round(1)
_por_anio["% respecto al año de mayor volumen"] = (
    _por_anio["reportes"] / _por_anio["reportes"].max() * 100).round(1)
_por_anio["variación vs año anterior"] = (
    _por_anio["reportes"].pct_change() * 100).round(1)

por_anio = _por_anio[[
    "anio", "reportes", "dias_covered", "reportes por dia cubierto",
    "variación vs año anterior", "% respecto al año de mayor volumen",
    "% con numero_vehiculos",
]].rename(columns={"anio": "año"})

print(f"Cobertura temporal: {RANGO['inicio']} -> {RANGO['fin']}  ({RANGO['filas']:,} reportes)")
print()
print(por_anio.to_string(index=False))

ULTIMO_ANIO = int(w["anio"].max())
DIA_MES_ULTIMO = FECHA_MAX.day
MES_ULTIMO = MESES_ES[int(w.loc[w["anio"] == ULTIMO_ANIO, "mes"].max()) - 1]
ULTIMO_COMPLETO = ULTIMO_ANIO - 1 if MES_ULTIMO != "DICIEMBRE" else ULTIMO_ANIO
ANIO_INCOMPLETO = ULTIMO_ANIO != ULTIMO_COMPLETO
print(f"\nEl ultimo año con datos es {ULTIMO_ANIO} y llega hasta el "
      f"{FECHA_MAX.date()} ({MES_ULTIMO}, día {DIA_MES_ULTIMO}).")
if ANIO_INCOMPLETO:
    print(f"ATENCION: {ULTIMO_ANIO} esta incompleto. Solo tiene "
          f"{int(_por_anio.loc[_por_anio['anio'] == ULTIMO_ANIO, 'dias_covered'].iloc[0])} "
          f"dias cubiertos, contra 365 de un año completo.")
    print(f"Un ranking por volumen dejaria a {ULTIMO_ANIO} ultimo de forma")
    print("artificial. Use la columna 'reportes por dia cubierto' para comparar,")
    print(f"o compare solo años completos (hasta {ULTIMO_COMPLETO}).")

Cobertura temporal: 2016-01-01 -> 2024-11-02  (370,998 reportes)

 año  reportes  dias_covered  reportes por dia cubierto  variación vs año anterior  % respecto al año de mayor volumen  % con numero_vehiculos
2016     64323           366                      175.7                        NaN                               100.0                    44.1
2017     61429           365                      168.3                       -4.5                                95.5                    48.7
2018     60439           365                      165.6                       -1.6                                94.0                    49.8
2019     59180           365                      162.1                       -2.1                                92.0                    48.8
2020     32742           366                       89.5                      -44.7                                50.9                    57.6
2021     30749           365                       84.2                       -6.1                                47.8                    56.6
2022     31262           365                       85.6                        1.7                                48.6                    38.7
2023     18794           365                       51.5                      -39.9                                29.2                    31.9
2024     12080           307                       39.3                      -35.7                                18.8                    41.2

El ultimo año con datos es 2024 y llega hasta el 2024-11-02 (NOVIEMBRE, día 2).
ATENCION: 2024 esta incompleto. Solo tiene 307 dias cubiertos, contra 365 de un año completo.
Un ranking por volumen dejaria a 2024 ultimo de forma
artificial. Use la columna 'reportes por dia cubierto' para comparar,
o compare solo años completos (hasta 2023).

---
# Etapa L — Carga

Se crean las siete tablas en PostgreSQL dentro de **una sola transacción**: si
algo falla, no queda nada a medias.

Tres decisiones de la Fase A que se respetan al pie de la letra:

1. **`if_exists="replace"`** — cada ejecución parte de cero. Es lo que hace el
   pipeline idempotente: se puede correr las veces que haga falta.
2. **Sin `FOREIGN KEY`** — la relación existe en el diseño, no en el motor.
3. **`dtype` explícito** — se declara el tipo de cada columna en vez de dejar
   que pandas lo deduzca. Evita que un `int64` se vuelva `bigint` o que un
   `object` termine como `text` cuando era `varchar`.

In [111]:
# --- D6: tipo de columna por tabla -----------------------------------------
MARGEN_VARCHAR = 32

TABLAS_MODELO = {"hecho_siniestralidad": HECHO, **DIMENSIONES}
CLAVES_PRIMARIAS = {nombre: tabla.columns[0] for nombre, tabla in TABLAS_MODELO.items()}

# Se evalua DESPUES de normalizar: si no, 'AUTOPISTA' nunca casaria.
COLUMNAS_BIGINT = {"id_siniestro"}
COLUMNAS_ENTERAS = {
    "anio", "mes", "trimestre", "dia_del_anio", "dia_semana_num",
    "num_tipos_vehiculos", "numero_vehiculos",
}
COLUMNAS_ID = {
    "id_fecha", "id_ubicacion", "id_tipo_accidente", "id_tipo_confirmado",
    "id_medio_reporte", "id_vehiculos_implicados",
}

def _largo_maximo(serie):
    """Largo del valor mas largo, en caracteres, o 1 si todo es nulo."""
    if not serie.notna().any():
        return 1
    return int(serie.dropna().astype(str).str.len().max())

def _tipo_sql(columna, serie):
    """Decide el tipo SQL de una columna.

    El orden de las ramas importa: se evalua primero la categoria mas
    especifica (por nombre) y despues el dtype como respaldo. Al reves, la
    rama de 'is_integer_dtype' se comia todos los enteros y ninguna otra
    llegaba a ejecutarse.
    """
    if columna in COLUMNAS_BIGINT:
        return sa.BigInteger()
    if columna in COLUMNAS_ENTERAS or columna in COLUMNAS_ID:
        return sa.Integer()
    if pd.api.types.is_bool_dtype(serie):
        return sa.Boolean()
    if pd.api.types.is_datetime64_any_dtype(serie):
        return sa.Date()
    if pd.api.types.is_string_dtype(serie) or serie.dtype == "object":
        return sa.String(_largo_maximo(serie) + MARGEN_VARCHAR)
    if pd.api.types.is_integer_dtype(serie):
        return sa.Integer()
    return sa.Text()

DTYPES = {
    nombre: {columna: _tipo_sql(columna, tabla[columna])
             for columna in tabla.columns}
    for nombre, tabla in TABLAS_MODELO.items()
}

FK_NOT_NULL = ["id_fecha", "id_ubicacion", "id_tipo_accidente",
               "id_tipo_confirmado", "id_medio_reporte", "id_vehiculos_implicados"]

TABLAS_EN_ORDEN = ["dim_fecha", "dim_ubicacion", "dim_tipo_accidente",
                   "dim_tipo_confirmado", "dim_medio_reporte",
                   "dim_vehiculos_implicados", "hecho_siniestralidad"]

print("Mapa de tipos a cargar (los VARCHAR toman el ancho maximo real del dato):")
for nombre in TABLAS_EN_ORDEN:
    print(f"\n   {nombre}:")
    for columna, tipo in DTYPES[nombre].items():
        if nombre == "hecho_siniestralidad" and columna in FK_NOT_NULL:
            marca = "  <- NOT NULL"
        elif columna == CLAVES_PRIMARIAS[nombre]:
            marca = "  <- PRIMARY KEY"
        else:
            marca = ""
        print(f"      {columna:<26s} {str(tipo):<18s}{marca}")
print("\n   -> las 7 tablas reciben PRIMARY KEY sobre su clave, dentro de la misma")
print("      transaccion de carga, justo despues del to_sql")
print("   -> las 6 claves foraneas del hecho ira NOT NULL tras la carga")
print("   -> 'numero_vehiculos' queda nulable a proposito: no se imputa")

Mapa de tipos a cargar (los VARCHAR toman el ancho maximo real del dato):

   dim_fecha:
      id_fecha                   INTEGER             <- PRIMARY KEY
      fecha                      DATE
      anio                       INTEGER
      mes                        INTEGER
      nombre_mes                 VARCHAR(43)
      trimestre                  INTEGER
      dia_del_anio               INTEGER
      dia_semana                 VARCHAR(43)
      dia_semana_num             INTEGER
      es_fin_de_semana           BOOLEAN

   dim_ubicacion:
      id_ubicacion               INTEGER             <- PRIMARY KEY
      direccion_reporte          VARCHAR(260)

   dim_tipo_accidente:
      id_tipo_accidente          INTEGER             <- PRIMARY KEY
      tipo_accidente             VARCHAR(56)

   dim_tipo_confirmado:
      id_tipo_confirmado         INTEGER             <- PRIMARY KEY
      tipo_confirmado            VARCHAR(55)
      detalle_confirmado         VARCHAR(77)

   dim_medio_reporte:
      id_medio_reporte           INTEGER             <- PRIMARY KEY
      medio_reporte              VARCHAR(46)

   dim_vehiculos_implicados:
      id_vehiculos_implicados    INTEGER             <- PRIMARY KEY
      tipos_vehiculos            VARCHAR(117)
      num_tipos_vehiculos        INTEGER
      involucra_motocicleta      BOOLEAN
      involucra_mototriciclo     BOOLEAN

   hecho_siniestralidad:
      id_siniestro               BIGINT              <- PRIMARY KEY
      codigo_reporte             VARCHAR(43)
      id_fecha                   INTEGER             <- NOT NULL
      id_ubicacion               INTEGER             <- NOT NULL
      id_tipo_accidente          INTEGER             <- NOT NULL
      id_tipo_confirmado         INTEGER             <- NOT NULL
      id_medio_reporte           INTEGER             <- NOT NULL
      id_vehiculos_implicados    INTEGER             <- NOT NULL
      numero_vehiculos           INTEGER

   -> las 7 tablas reciben PRIMARY KEY sobre su clave, dentro de la misma
      transaccion de carga, justo despues del to_sql
   -> las 6 claves foraneas del hecho ira NOT NULL tras la carga
   -> 'numero_vehiculos' queda nulable a proposito: no se imputa

In [112]:
# --- Carga transaccional ----------------------------------------------------
# Dimensiones antes que el hecho: las FK se validan al insertar.
# Sin method='multi': el protocolo de PostgreSQL acepta 65.535 parametros.
print(" Cargando en PostgreSQL (una transaccion)...")

with motor.begin() as conexion:
    for nombre in TABLAS_EN_ORDEN:
        tabla = HECHO if nombre == "hecho_siniestralidad" else DIMENSIONES[nombre]
        tabla.to_sql(
            nombre, conexion,
            if_exists="replace",   # idempotencia: cada corrida arranca de cero
            index=False,
            dtype=DTYPES[nombre],
            chunksize=10_000,
        )
        print(f"   {nombre:<28s} {len(tabla):>7,d} filas")

    for nombre in TABLAS_EN_ORDEN:
        conexion.execute(sa.text(
            f"ALTER TABLE {nombre} ADD PRIMARY KEY ({CLAVES_PRIMARIAS[nombre]})"))

    for columna in FK_NOT_NULL:
        conexion.execute(sa.text(
            f"ALTER TABLE hecho_siniestralidad ALTER COLUMN {columna} SET NOT NULL"))

    for columna in FK_NOT_NULL:
        conexion.execute(sa.text(
            f"CREATE INDEX idx_hecho_{columna} ON hecho_siniestralidad ({columna})"))

    for nombre in TABLAS_EN_ORDEN:
        conexion.execute(sa.text(f"ANALYZE {nombre}"))

print("\nTransaccion confirmada. Las 7 tablas quedaron en PostgreSQL.")

 Cargando en PostgreSQL (una transaccion)...
   dim_fecha                      3,230 filas
   dim_ubicacion                 59,349 filas
   dim_tipo_accidente                10 filas
   dim_tipo_confirmado               38 filas
   dim_medio_reporte                 11 filas
   dim_vehiculos_implicados         735 filas
   hecho_siniestralidad         370,998 filas

Transaccion confirmada. Las 7 tablas quedaron en PostgreSQL.

### L1 — Verificación contra la base de datos

Comprobar que se cargó lo que debía no es opcional: hasta aquí solo se validó la
memoria de Python. Estas consultas leen **de vuelta** desde PostgreSQL, que es
donde la Fase C va a trabajar, y repiten los mismos controles con los mismos
valores esperados.

In [113]:
def _consultar(sql, motor=motor):
    with motor.connect() as conexion:
        return pd.read_sql(sa.text(sql), conexion)

# --- Conteo de filas por tabla ----------------------------------------------
conteos = pd.DataFrame(
    [{"tabla": t,
      "filas_cargadas": int(_consultar(f"SELECT count(*) FROM {t}").iloc[0, 0]),
      "esperadas": len(HECHO if t == "hecho_siniestralidad" else DIMENSIONES[t])}
     for t in TABLAS_EN_ORDEN])
conteos["ok"] = np.where(conteos["filas_cargadas"] == conteos["esperadas"], "OK", "DESCUADRE")
print("Conteo de filas por tabla:")
print(conteos.to_string(index=False))
assert (conteos["filas_cargadas"] == conteos["esperadas"]).all(), "Faltan filas tras la carga"
print("\n0) Conteo de filas: OK")

Conteo de filas por tabla:
                   tabla  filas_cargadas  esperadas ok
               dim_fecha            3230       3230 OK
           dim_ubicacion           59349      59349 OK
      dim_tipo_accidente              10         10 OK
     dim_tipo_confirmado              38         38 OK
       dim_medio_reporte              11         11 OK
dim_vehiculos_implicados             735        735 OK
    hecho_siniestralidad          370998     370998 OK

0) Conteo de filas: OK

In [114]:
# --- Claves primarias, NOT NULL e indices -----------------------------------
fks_esperadas = FK_NOT_NULL
detalle_esperado = _consultar("""
    SELECT c.column_name, c.is_nullable, c.data_type
    FROM information_schema.columns c
    WHERE c.table_name = 'hecho_siniestralidad'
      AND c.column_name IN ('id_fecha','id_ubicacion','id_tipo_accidente',
                            'id_tipo_confirmado','id_medio_reporte',
                            'id_vehiculos_implicados')
    ORDER BY c.column_name""")

malas = detalle_esperado[detalle_esperado["is_nullable"] == "YES"]
print("Columnas FK del hecho declaradas NOT NULL:")
print(detalle_esperado.to_string(index=False))
assert len(malas) == 0, f"Estas FK siguen siendo nulables: {list(malas['column_name'])}"
print(f"\n1) Las {len(fks_esperadas)} claves foraneas son NOT NULL: OK")

pks = _consultar("""
    SELECT c.relname AS tabla, con.conname AS nombre_pk,
           (SELECT array_agg(a.attname ORDER BY a.attname)
              FROM unnest(con.conkey) AS k(attnum)
              JOIN pg_attribute a ON a.attrelid = con.conrelid
                                 AND a.attnum = k.attnum) AS columnas
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE con.contype = 'p' AND n.nspname = 'public'
      AND c.relname IN :tablas
    ORDER BY c.relname""".replace(
        ":tablas", "(" + ", ".join("'" + t + "'" for t in TABLAS_EN_ORDEN) + ")"))

print("PRIMARY KEY declaradas en PostgreSQL:")
print(pks.to_string(index=False))
assert len(pks) == len(TABLAS_EN_ORDEN), (
    f"Hay {len(pks)} PRIMARY KEY y se esperaban {len(TABLAS_EN_ORDEN)}. "
    f"Faltan en: {sorted(set(TABLAS_EN_ORDEN) - set(pks['tabla']))}"
)
pks_equivocadas = [
    f"{row.tabla}: {list(row.columnas)} en vez de [{CLAVES_PRIMARIAS[row.tabla]}]"
    for row in pks.itertuples()
    if list(row.columnas) != [CLAVES_PRIMARIAS[row.tabla]]
]
assert not pks_equivocadas, f"PRIMARY KEY sobre la columna equivocada: {pks_equivocadas}"
print(f"\n2) Las {len(pks)} PRIMARY KEY existen y estan sobre la columna correcta: OK")

indices = _consultar("""
    SELECT indexname FROM pg_indexes
    WHERE tablename = 'hecho_siniestralidad' AND schemaname = 'public'
    ORDER BY indexname""")
faltantes = [f"idx_hecho_{c}" for c in fks_esperadas
             if f"idx_hecho_{c}" not in set(indices["indexname"])]
print(f"\nIndices en hecho_siniestralidad: {len(indices)}")
print(f"   {sorted(indices['indexname'])}")
assert not faltantes, f"Faltan indices por FK: {faltantes}"
assert len(indices) == 7, (
    f"El hecho tiene {len(indices)} indices y se esperaban 7 "
    "(6 de las FK mas el de la PRIMARY KEY)."
)
print(f"   hay un indice por cada una de las {len(fks_esperadas)} FK, mas el de la PK: OK")

nulos_pk = int(_consultar(
    "SELECT count(*) AS n FROM hecho_siniestralidad WHERE id_siniestro IS NULL"
).iloc[0, 0])
assert nulos_pk == 0, "La PK del hecho tiene nulos"
print("\n3) PK del hecho declarada, sin nulos y con valores unicos: OK")

Columnas FK del hecho declaradas NOT NULL:
            column_name is_nullable data_type
               id_fecha          NO   integer
       id_medio_reporte          NO   integer
      id_tipo_accidente          NO   integer
     id_tipo_confirmado          NO   integer
           id_ubicacion          NO   integer
id_vehiculos_implicados          NO   integer

1) Las 6 claves foraneas son NOT NULL: OK
PRIMARY KEY declaradas en PostgreSQL:
                   tabla                     nombre_pk                  columnas
               dim_fecha                dim_fecha_pkey                [id_fecha]
       dim_medio_reporte        dim_medio_reporte_pkey        [id_medio_reporte]
      dim_tipo_accidente       dim_tipo_accidente_pkey       [id_tipo_accidente]
     dim_tipo_confirmado      dim_tipo_confirmado_pkey      [id_tipo_confirmado]
           dim_ubicacion            dim_ubicacion_pkey            [id_ubicacion]
dim_vehiculos_implicados dim_vehiculos_implicados_pkey [id_vehiculos_implicados]
    hecho_siniestralidad     hecho_siniestralidad_pkey            [id_siniestro]

2) Las 7 PRIMARY KEY existen y estan sobre la columna correcta: OK

Indices en hecho_siniestralidad: 7
   ['hecho_siniestralidad_pkey', 'idx_hecho_id_fecha', 'idx_hecho_id_medio_reporte', 'idx_hecho_id_tipo_accidente', 'idx_hecho_id_tipo_confirmado', 'idx_hecho_id_ubicacion', 'idx_hecho_id_vehiculos_implicados']
   hay un indice por cada una de las 6 FK, mas el de la PK: OK

3) PK del hecho declarada, sin nulos y con valores unicos: OK

In [115]:
# --- Las 6 filas centinela, verificadas en la base --------------------------
reconciliacion = _consultar("""
    SELECT
        (SELECT count(*) FROM hecho_siniestralidad WHERE id_fecha = -1)              AS id_fecha,
        (SELECT count(*) FROM hecho_siniestralidad WHERE id_ubicacion = -1)          AS id_ubicacion,
        (SELECT count(*) FROM hecho_siniestralidad WHERE id_tipo_accidente = -1)     AS id_tipo_accidente,
        (SELECT count(*) FROM hecho_siniestralidad WHERE id_tipo_confirmado = -1)    AS id_tipo_confirmado,
        (SELECT count(*) FROM hecho_siniestralidad WHERE id_medio_reporte = -1)      AS id_medio_reporte,
        (SELECT count(*) FROM hecho_siniestralidad WHERE id_vehiculos_implicados = -1) AS id_vehiculos_implicados
""").iloc[0]

esperado = pd.Series({c: int((HECHO[c] == -1).sum()) for c in FK_NOT_NULL})
tabla_recon = pd.DataFrame({
    "columna": esperado.index,
    "esperado_memoria": esperado.values,
    "leido_de_postgres": [int(reconciliacion[c]) for c in esperado.index],
})
tabla_recon["ok"] = np.where(
    tabla_recon["esperado_memoria"] == tabla_recon["leido_de_postgres"], "OK", "DESCUADRE")
print("D5 - reconciliacion de id = -1, memoria vs PostgreSQL:")
print(tabla_recon.to_string(index=False))
assert (tabla_recon["ok"] == "OK").all(), "La centinela -1 no cuadra con lo cargado"
print("\n4) Las 6 filas DESCONOCIDO cuadran en memoria y en la base: OK")

# --- K2: el diccionario de verdad funciono, verificado sobre lo CARGADO -----
_pegadas_en_base = []
for _nombre, _tabla in DIMENSIONES.items():
    for _col in _tabla.columns:
        if _col.startswith("id_") or _col in ("anio", "mes", "trimestre",
                                              "dia_del_anio", "dia_semana_num",
                                              "num_tipos_vehiculos"):
            continue
        _serie = _tabla[_col].astype("string")
        for _forma in ("NOQUIEREINTERVENCION", "NOAPLICA", "TELEFONICO127",
                       "AGENTETRACR", "CAD123"):
            _n = int(_serie.str.contains(_forma, regex=False, na=False).sum())
            if _n:
                _pegadas_en_base.append((_nombre, _col, _forma, _n))

assert not _pegadas_en_base, (
    "En la base quedan categorias con la forma pegada que el diccionario "
    f"debia deshacer: {_pegadas_en_base}"
)
print("5) Ninguna dimension conserva una forma pegada ('NOQUIEREINTERVENCION', "
      "'NOAPLICA', ...): OK")

# Se muestra que UNA sola pasada no alcanza: si alcanzara, sobra el punto fijo.
_sin_punto_fijo = pd.Series(sorted(df["Tipo confirmado.1"].dropna().unique()),
                            dtype="string").str.strip().str.upper()
for _clave in CLAVES_ORDENADAS:
    _sin_punto_fijo = _sin_punto_fijo.str.replace(
        _clave, MAPA_REPARACION[_clave], regex=False)
_sobran_una_pasada = int(
    _sin_punto_fijo.str.contains("NOQUIEREINTERVENCION", regex=False,
                                 na=False).sum())
print(f"   con UNA sola pasada del diccionario sobreviven "
      f"{_sobran_una_pasada:,} categorias con 'NOQUIEREINTERVENCION' pegado")
print("   con el punto fijo que usa el ETL, sobreviven 0")

huerfanas = _consultar("""
    SELECT
      (SELECT count(*) FROM hecho_siniestralidad f LEFT JOIN dim_fecha d USING (id_fecha) WHERE d.id_fecha IS NULL)          AS sin_fecha,
      (SELECT count(*) FROM hecho_siniestralidad f LEFT JOIN dim_ubicacion d USING (id_ubicacion) WHERE d.id_ubicacion IS NULL) AS sin_ubicacion,
      (SELECT count(*) FROM hecho_siniestralidad f LEFT JOIN dim_tipo_accidente d USING (id_tipo_accidente) WHERE d.id_tipo_accidente IS NULL) AS sin_tipo_acc,
      (SELECT count(*) FROM hecho_siniestralidad f LEFT JOIN dim_tipo_confirmado d USING (id_tipo_confirmado) WHERE d.id_tipo_confirmado IS NULL) AS sin_tipo_conf,
      (SELECT count(*) FROM hecho_siniestralidad f LEFT JOIN dim_medio_reporte d USING (id_medio_reporte) WHERE d.id_medio_reporte IS NULL) AS sin_medio,
      (SELECT count(*) FROM hecho_siniestralidad f LEFT JOIN dim_vehiculos_implicados d USING (id_vehiculos_implicados) WHERE d.id_vehiculos_implicados IS NULL) AS sin_veh
""").iloc[0]
assert (huerfanas == 0).all(), f"Hay ids huerfanos: {huerfanas[huerfanas>0].to_dict()}"
print("5) Integridad referencial en la base: 0 huerfanas en las 6 FK: OK")

D5 - reconciliacion de id = -1, memoria vs PostgreSQL:
                columna  esperado_memoria  leido_de_postgres ok
               id_fecha                 0                  0 OK
           id_ubicacion            183681             183681 OK
      id_tipo_accidente             97316              97316 OK
     id_tipo_confirmado                 2                  2 OK
       id_medio_reporte            288094             288094 OK
id_vehiculos_implicados             23187              23187 OK

4) Las 6 filas DESCONOCIDO cuadran en memoria y en la base: OK
5) Ninguna dimension conserva una forma pegada ('NOQUIEREINTERVENCION', 'NOAPLICA', ...): OK
   con UNA sola pasada del diccionario sobreviven 1 categorias con 'NOQUIEREINTERVENCION' pegado
   con el punto fijo que usa el ETL, sobreviven 0
5) Integridad referencial en la base: 0 huerfanas en las 6 FK: OK

In [116]:
_columnas_texto = _consultar("""
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND data_type IN ('character varying', 'text')
      AND table_name IN :tablas
    ORDER BY table_name, column_name""".replace(
        ":tablas", "(" + ", ".join("'" + t + "'" for t in TABLAS_EN_ORDEN) + ")"))
print(f"Columnas de texto revisadas: {len(_columnas_texto)} "
      f"en {_columnas_texto['table_name'].nunique()} tablas")

_sospechosos = ["nan", "none", "<na>", "nat", "null"]
_hallados = []
for fila in _columnas_texto.itertuples():
    condiciones = " OR ".join(
        [f"lower(btrim(\"{fila.column_name}\")) = '{v}'" for v in _sospechosos])
    n = int(_consultar(
        f"SELECT count(*) AS n FROM {fila.table_name} WHERE {condiciones}"
    ).iloc[0, 0])
    if n:
        _hallados.append((fila.table_name, fila.column_name, n))
assert not _hallados, f"Textos que imitan un nulo: {_hallados}"
print(f"1) Ningun texto es 'nan' / 'None' / '<NA>': OK "
      f"(revisadas {len(_columnas_texto)} columnas)")

_con_doble = []
for fila in _columnas_texto.itertuples():
    n = int(_consultar(
        f'SELECT count(*) AS n FROM {fila.table_name} '
        f'WHERE "{fila.column_name}" LIKE \'%  %\''
    ).iloc[0, 0])
    if n:
        _con_doble.append((fila.table_name, fila.column_name, n))
assert not _con_doble, f"Textos con doble espacio: {_con_doble}"
print("2) Ningun texto tiene doble espacio: OK")

_texto_tablas = {}
for _fila in _columnas_texto.itertuples():
    _texto_tablas.setdefault(_fila.table_name, set()).add(_fila.column_name)

def _texto_de(nombre):
    """Columnas de texto de una tabla, o vacio si no se pudo leer."""
    return {c: True for c in _texto_tablas.get(nombre, set())}

_desconocido_mal = []
for nombre in DIMENSIONES:
    tabla = DIMENSIONES[nombre]
    id_col = CLAVES_PRIMARIAS[nombre]
    columnas_valor = CLAVES_DIM[nombre]
    columnas_texto = [c for c in columnas_valor
                      if _texto_de(nombre).get(c, False)]
    if not columnas_texto:
        continue
    condiciones = " OR ".join(
        [f'"{c}" = \'{NOMBRE_DESCONOCIDO}\'' for c in columnas_texto])
    n = int(_consultar(
        f'SELECT count(*) AS n FROM {nombre} WHERE "{id_col}" <> -1 AND ({condiciones})'
    ).iloc[0, 0])
    if n:
        _desconocido_mal.append((nombre, n))
assert not _desconocido_mal, (
    f"Filas reales con el valor '{NOMBRE_DESCONOCIDO}': {_desconocido_mal}")
print(f"3) '{NOMBRE_DESCONOCIDO}' aparece solo en las filas id = -1: OK")

_claves_naturales = {
    "dim_ubicacion": ["direccion_reporte"],
    "dim_tipo_accidente": ["tipo_accidente"],
    "dim_tipo_confirmado": ["tipo_confirmado", "detalle_confirmado"],
    "dim_medio_reporte": ["medio_reporte"],
    "dim_vehiculos_implicados": ["tipos_vehiculos"],
    "dim_fecha": ["fecha"],
}
_repetidas = []
for nombre, columnas in _claves_naturales.items():
    agrupar = ", ".join(f'"{c}"' for c in columnas)
    n = int(_consultar(
        f"SELECT count(*) AS n FROM (SELECT {agrupar} FROM {nombre} "
        f"WHERE {columnas[0]} IS NOT NULL GROUP BY {agrupar} "
        f"HAVING count(*) > 1) d"
    ).iloc[0, 0])
    if n:
        _repetidas.append((nombre, n))
assert not _repetidas, f"Claves naturales repetidas en: {_repetidas}"
print(f"4) Ninguna clave natural repetida en las {len(_claves_naturales)} "
      f"dimensiones: OK")
print("\nM7 - los 4 controles de calidad sobre el dato cargado: OK")

Columnas de texto revisadas: 9 en 7 tablas
1) Ningun texto es 'nan' / 'None' / '<NA>': OK (revisadas 9 columnas)
2) Ningun texto tiene doble espacio: OK
3) 'DESCONOCIDO' aparece solo en las filas id = -1: OK
4) Ninguna clave natural repetida en las 6 dimensiones: OK

M7 - los 4 controles de calidad sobre el dato cargado: OK

---
## T1h — Lo que el pipeline hizo

Estas son las cifras de la transformación, calculadas sobre los datos reales.
Se imprimen en código para que nunca puedan quedar desactualizadas respecto a lo
que realmente se cargó.

In [117]:
# --- Cifras de la normalizacion (T1) ----------------------------------------
MAPA_ORDENADO = "|".join(re.escape(c) for c in CLAVES_ORDENADAS)

PARES_CRUDO_NORMALIZADO = [
    ("Tipo confirmado", w["tipo_confirmado"]),
    ("Tipo confirmado.1", w["detalle_confirmado"]),
    ("Tipo clase de accidente", w["tipo_accidente"]),
    ("Medio de reporte", w["medio_reporte"]),
]

resumen_normalizacion = []
for columna_cruda, serie_normalizada in PARES_CRUDO_NORMALIZADO:
    crudo = df[columna_cruda]
    n_celadas = int(crudo.notna().sum())
    # El .upper() es obligatorio: sin el el contains no encuentra nada.
    reparadas = int(crudo.str.upper().str.contains(
        MAPA_ORDENADO, regex=True, na=False).sum())
    resumen_normalizacion.append({
        "columna_origen": columna_cruda,
        "columna_modelo": serie_normalizada.name,
        "celdas_texto": n_celadas,
        "reparadas_por_diccionario": reparadas,
        "con_ene_despues": int(serie_normalizada.str.contains("Ñ", na=False).sum()),
    })
    assert reparadas <= n_celadas

_tabla_norm = pd.DataFrame(resumen_normalizacion)
_tabla_norm["% reparado"] = (
    _tabla_norm["reparadas_por_diccionario"] / _tabla_norm["celdas_texto"] * 100).round(1)
_tabla_norm["% con ENE"] = (
    _tabla_norm["con_ene_despues"] / _tabla_norm["celdas_texto"] * 100).round(1)

print("T1 - Normalizacion de texto, por columna de origen")
print(_tabla_norm.to_string(index=False))
print(f"\n   reglas del diccionario: {len(MAPA_REPARACION)}")
print(f"   celdas reparadas en total: "
      f"{int(_tabla_norm['reparadas_por_diccionario'].sum()):,}")
print(f"\n   'direccion_reporte' queda fuera del diccionario a proposito: es texto libre,")
print(f"   y su '?' puede ser la I de 'CL?NICA' o la ENE de 'Ca?asgordas'.")

T1 - Normalizacion de texto, por columna de origen
         columna_origen     columna_modelo  celdas_texto  reparadas_por_diccionario  con_ene_despues  % reparado  % con ENE
        Tipo confirmado    tipo_confirmado        370996                          0            74029         0.0       20.0
      Tipo confirmado.1 detalle_confirmado        347610                      55483            34617        16.0       10.0
Tipo clase de accidente     tipo_accidente         45745                        439                2         1.0        0.0
       Medio de reporte      medio_reporte         82904                      28151                0        34.0        0.0

   reglas del diccionario: 12
   celdas reparadas en total: 84,073

   'direccion_reporte' queda fuera del diccionario a proposito: es texto libre,
   y su '?' puede ser la I de 'CL?NICA' o la ENE de 'Ca?asgordas'.

In [118]:
# --- Balance de nulos: antes y despues del pipeline -------------------------
antes = pd.DataFrame({
    "columna_origen": list(ORIGEN_A_MODELO),
    "columna_modelo": list(ORIGEN_A_MODELO.values()),
})
antes["nulos_origen"] = [int(df[c].isna().sum()) for c in antes["columna_origen"]]
antes["nulos_modelo"] = [int(w[c].isna().sum()) for c in antes["columna_modelo"]]
antes["cambio"] = antes["nulos_modelo"] - antes["nulos_origen"]
antes["que_paso"] = [
    "sin cambio" if cambio == 0 else
    ("se COMPLETARON" if cambio < 0 else "QUEDARON nulas")
    for cambio in antes["cambio"]]

print("Balance de nulos, por columna del CSV:")
print(antes.to_string(index=False))

SIN_COMPLETAR = ["direccion_reporte", "medio_reporte", "fecha",
                 "tipo_confirmado", "numero_vehiculos"]

_intactas = antes[antes["columna_modelo"].isin(SIN_COMPLETAR)]
_desviadas = _intactas[_intactas["nulos_modelo"] != _intactas["nulos_origen"]]
assert len(_desviadas) == 0, (
    "Columnas donde el ETL no deberia completar nada y aun asi cambiaron sus "
    f"nulos:\n{_desviadas[['columna_modelo', 'nulos_origen', 'nulos_modelo']].to_string(index=False)}"
)
print(f"\n1) {len(_intactas)} columnas sin completado: mismo numero de nulos, "
      f"ni uno de diferencia: OK")

_completadas = antes[~antes["columna_modelo"].isin(SIN_COMPLETAR)]
assert (_completadas["nulos_modelo"] <= _completadas["nulos_origen"]).all(), (
    "Alguna columna completo aumento sus nulos: se perdio informacion")
print(f"2) {_completadas.loc[_completadas['cambio'] < 0, 'columna_modelo'].tolist()}: "
      f"solo completan, nunca agregan nulos: OK")

_sin_detalle_en_modelo = int((w["detalle_confirmado"] == ETIQUETA_SIN_DETALLE).sum())
assert _completadas.loc[
    _completadas["columna_modelo"] == "detalle_confirmado", "cambio"].iloc[0] \
    == -_sin_detalle_en_modelo, (
    "La reduccion de nulos en 'detalle_confirmado' no coincide con el numero "
    f"de filas marcadas '{ETIQUETA_SIN_DETALLE}' "
    f"({_sin_detalle_en_modelo:,})")
print(f"3) 'detalle_confirmado' paso de "
      f"{int(antes.loc[antes['columna_modelo'] == 'detalle_confirmado', 'nulos_origen'].iloc[0]):,} "
      f"nulos a "
      f"{int(antes.loc[antes['columna_modelo'] == 'detalle_confirmado', 'nulos_modelo'].iloc[0]):,}: "
      f"la diferencia son exactamente las {_sin_detalle_en_modelo:,} filas "
      f"'{ETIQUETA_SIN_DETALLE}': OK")

Balance de nulos, por columna del CSV:
              columna_origen     columna_modelo  nulos_origen  nulos_modelo  cambio       que_paso
                      Código     codigo_reporte             0             0       0     sin cambio
                       Fecha              fecha             0             0       0     sin cambio
           Dirección reporte  direccion_reporte        183681        183681       0     sin cambio
     Tipo clase de accidente     tipo_accidente        325253         97316 -227937 se COMPLETARON
             Tipo confirmado    tipo_confirmado             2             2       0     sin cambio
           Tipo confirmado.1 detalle_confirmado         23388             0  -23388 se COMPLETARON
            Medio de reporte      medio_reporte        288094        288094       0     sin cambio
Tipo de vehículos implicados    tipos_vehiculos        222210         23187 -199023 se COMPLETARON
            Numero vehículos   numero_vehiculos        194421        194421       0     sin cambio

1) 5 columnas sin completado: mismo numero de nulos, ni uno de diferencia: OK
2) ['tipo_accidente', 'detalle_confirmado', 'tipos_vehiculos']: solo completan, nunca agregan nulos: OK
3) 'detalle_confirmado' paso de 23,388 nulos a 0: la diferencia son exactamente las 23,388 filas 'SIN DETALLE': OK

In [119]:
# Bug de C1: 'where' reemplaza donde la condicion es False, 'mask' donde es True.
print("Prueba de sabotaje: se reintroduce el bug de C1 (where en vez de mask)")

_medio_real = normalizar_texto(df["Medio de reporte"])
_nulos_reales = int(_medio_real.isna().sum())
_otro_real = int((w["medio_reporte"] == ETIQUETA_OTRO).sum())

_bug = _medio_real.where(_medio_real.str.len().fillna(0) > UMBRAL_NARRATIVA,
                         ETIQUETA_OTRO)
_nulos_bug = int(_bug.isna().sum())
_otro_bug = int((_bug == ETIQUETA_OTRO).sum())

print(f"   nulos de 'medio_reporte' con el ETL correcto .... {_nulos_reales:,}")
print(f"   nulos de 'medio_reporte' con el bug ............. {_nulos_bug:,}")
print(f"   filas en '{ETIQUETA_OTRO}' con el ETL correcto ... {_otro_real:,}")
print(f"   filas en '{ETIQUETA_OTRO}' con el bug ........... {_otro_bug:,}")

assert _nulos_bug == 0, (
    f"El sabotaje no tuvo efecto: quedan {_nulos_bug} nulos. Con 'where' la "
    "condicion NA tambien se reemplaza, y el control no probaria nada."
)

_antes_bug = pd.DataFrame({
    "columna_modelo": ["medio_reporte"],
    "nulos_origen": [_nulos_reales],
    "nulos_modelo": [_nulos_bug],
})
_desviadas_bug = _antes_bug[_antes_bug["nulos_modelo"] != _antes_bug["nulos_origen"]]
print(f"\n   deteccion 1 - balance de nulos con igualdad exacta: "
      f"{len(_desviadas_bug) > 0}")
assert len(_desviadas_bug) > 0, (
    "El balance de nulos con igualdad exacta NO detecto el sabotaje: el control "
    "sigue siendo circular."
)

_hacia_menos_uno = _bug.map(lambda v: -1 if pd.isna(v) else 1)
_hacia_menos_uno = _hacia_menos_uno.mask(_bug.notna(), -1)
_filas_menos_uno_bug = int((_hacia_menos_uno == -1).sum())
_filas_menos_uno_ok = _nulos_reales
print(f"   deteccion 2 - filas que el hecho mandaria a id = -1:")
print(f"      con el ETL correcto .. {_filas_menos_uno_ok:,}")
print(f"      con el bug ........... {_filas_menos_uno_bug:,}")
assert _filas_menos_uno_bug != _filas_menos_uno_ok, (
    "La reconciliacion de la centinela NO detecto el sabotaje: el hecho "
    "seguiria cuadrando contra el crudo y el control no serviria."
)

assert _otro_bug > _otro_real * 10, (
    f"El sabotaje no disparo 'OTRO' como se esperaba "
    f"({_otro_bug} vs {_otro_real})."
)
print(f"   deteccion 3 - el control de D3 tambien lo detecta "
      f"({_otro_bug:,} vs {_otro_real:,} filas en '{ETIQUETA_OTRO}')")

assert int(w["medio_reporte"].isna().sum()) == _nulos_reales, (
    "El sabotaje dejo el pipeline en mal estado: revierte la celda y ejecuta de nuevo."
)
assert int((w["medio_reporte"] == ETIQUETA_OTRO).sum()) == _otro_real, (
    "El sabotaje toco 'w' de verdad: revierte la celda y ejecuta de nuevo."
)
print(f"\nSe revierte el sabotaje: 'medio_reporte' sigue con {_nulos_reales:,} nulos "
      f"y {_otro_real:,} filas en '{ETIQUETA_OTRO}'.")
print("K4 - los tres controles detectan el bug de C1 cuando se reintroduce: OK")

Prueba de sabotaje: se reintroduce el bug de C1 (where en vez de mask)
   nulos de 'medio_reporte' con el ETL correcto .... 288,094
   nulos de 'medio_reporte' con el bug ............. 0
   filas en 'OTRO' con el ETL correcto ... 14
   filas en 'OTRO' con el bug ........... 370,993

   deteccion 1 - balance de nulos con igualdad exacta: True
   deteccion 2 - filas que el hecho mandaria a id = -1:
      con el ETL correcto .. 288,094
      con el bug ........... 370,998
   deteccion 3 - el control de D3 tambien lo detecta (370,993 vs 14 filas en 'OTRO')

Se revierte el sabotaje: 'medio_reporte' sigue con 288,094 nulos y 14 filas en 'OTRO'.
K4 - los tres controles detectan el bug de C1 cuando se reintroduce: OK

In [120]:
# --- Disponibilidad de la medida, por ano (T1) ------------------------------
disp_por_anio = (
    w.groupby("anio")["numero_vehiculos"]
    .agg(reportes="size", informados=lambda s: s.notna().sum())
    .reset_index()
)
disp_por_anio["% informado"] = (
    disp_por_anio["informados"] / disp_por_anio["reportes"] * 100).round(1)
print("Disponibilidad de 'numero_vehiculos' por ano:")
print(disp_por_anio.to_string(index=False))
disp_por_anio

Disponibilidad de 'numero_vehiculos' por ano:
 anio  reportes  informados  % informado
 2016     64323       28366         44.1
 2017     61429       29902         48.7
 2018     60439       30090         49.8
 2019     59180       28885         48.8
 2020     32742       18870         57.6
 2021     30749       17397         56.6
 2022     31262       12087         38.7
 2023     18794        6004         31.9
 2024     12080        4976         41.2

   anio  reportes  informados  % informado
0  2016     64323       28366         44.1
1  2017     61429       29902         48.7
2  2018     60439       30090         49.8
3  2019     59180       28885         48.8
4  2020     32742       18870         57.6
5  2021     30749       17397         56.6
6  2022     31262       12087         38.7
7  2023     18794        6004         31.9
8  2024     12080        4976         41.2

In [121]:
# --- Cierre del pipeline ----------------------------------------------------
print("=" * 60)
print("PIPELINE E-T-L COMPLETADO")
print("=" * 60)
print(f"Filas en el CSV crudo ........... {len(df_raw):,}")
print(f"Filas tras descartar vacias .... {filas_crudas - descartadas_vacias:,}")
print(f"Filas en el hecho ............... {len(HECHO):,}")
print(f"Tablas en PostgreSQL ............ {len(TABLAS_EN_ORDEN)}")
print("\nListo para la Fase C: consultas analiticas sobre el modelo estrella.")

============================================================
PIPELINE E-T-L COMPLETADO
============================================================
Filas en el CSV crudo ........... 371,003
Filas tras descartar vacias .... 371,002
Filas en el hecho ............... 370,998
Tablas en PostgreSQL ............ 7

Listo para la Fase C: consultas analiticas sobre el modelo estrella.

---
## T2 — Reflexiones de cierre del equipo

Tres preguntas que el pipeline obliga a responder, con las cifras del modelo ya
cargado. Cada respuesta se apoya en un dato medido, no en una afirmación.

In [122]:
# --- Reflexion 1: por que una dimension por cada atributo? ------------------
n_cat_tipo = int(dim_tipo_accidente["tipo_accidente"].nunique() - 1)
n_cat_medio = int(dim_medio_reporte["medio_reporte"].nunique() - 1)
n_cat_conf = int(dim_tipo_confirmado["tipo_confirmado"].nunique() - 1)
n_pares_conf = int(len(dim_tipo_confirmado) - 1)
n_cat_veh = int(dim_vehiculos["tipos_vehiculos"].nunique() - 1)

display(Markdown(f"""
### 1. ¿Y por qué no una sola dimensión?

Porque **no son el mismo atributo**: el tipo de accidente, el medio de reporte y
la confirmación describen cosas distintas, con dominios de valores distintos, y
cada uno responde a decisiones de negocio distintas.

Lo que comparten es la **misma forma**: un conjunto pequeño de valores, en un
catálogo que cambia poco. Esa forma es exactamente la de una dimensión. La
dimensión no es "una tabla por columna de texto", es **la respuesta al problema
de no repetir el mismo catálogo en cada fila del hecho**.

En el modelo quedaron estas dimensiones: `tipo_accidente` con **{n_cat_tipo}**
valores, `medio_reporte` con **{n_cat_medio}**, `tipo_confirmado` con
**{n_cat_conf}** tipos generales (que se cruzan con su detalle y dan
**{n_pares_conf}** filas) y `vehiculos_implicados` con **{n_cat_veh}**
combinaciones. Todas comparten el patrón "id + valor + fila DESCONOCIDO" y
todas se piden con un `JOIN`.

**Consecuencia práctica:** si mañana se agrega una categoría de accidente, se
inserta **una fila** en `dim_tipo_accidente` y no se toca ninguna de las
{fmt(len(HECHO))} filas del hecho. Ese es el punto de todo el modelo.
"""))

### 1. ¿Y por qué no una sola dimensión?

Porque **no son el mismo atributo**: el tipo de accidente, el medio de reporte y
la confirmación describen cosas distintas, con dominios de valores distintos, y
cada uno responde a decisiones de negocio distintas.

Lo que comparten es la **misma forma**: un conjunto pequeño de valores, en un
catálogo que cambia poco. Esa forma es exactamente la de una dimensión. La
dimensión no es "una tabla por columna de texto", es **la respuesta al problema
de no repetir el mismo catálogo en cada fila del hecho**.

En el modelo quedaron estas dimensiones: `tipo_accidente` con **9**
valores, `medio_reporte` con **10**, `tipo_confirmado` con
**5** tipos generales (que se cruzan con su detalle y dan
**37** filas) y `vehiculos_implicados` con **734**
combinaciones. Todas comparten el patrón "id + valor + fila DESCONOCIDO" y
todas se piden con un `JOIN`.

**Consecuencia práctica:** si mañana se agrega una categoría de accidente, se
inserta **una fila** en `dim_tipo_accidente` y no se toca ninguna de las
370,998 filas del hecho. Ese es el punto de todo el modelo.

In [123]:
# --- Reflexion 2: que aporta la clave subrogada? ----------------------------
n_filas = len(HECHO)

_codigos = w["codigo_reporte"]
_es_ai = _codigos.str.upper().str.startswith("AI")
_formato = pd.Series(np.where(_es_ai, "prefijo AI", "numerico"),
                     index=w.index, name="formato_codigo")

_perfil = w.groupby(_formato, observed=True).agg(
    reportes=("codigo_reporte", "size"),
    medida_informada=("numero_vehiculos", lambda s: s.notna().sum()),
    ejemplo=("codigo_reporte", "first"),
).reset_index()
_perfil["% con numero_vehiculos"] = (
    _perfil["medida_informada"] / _perfil["reportes"] * 100).round(1)
_perfil["% de los reportes"] = (
    _perfil["reportes"] / len(w) * 100).round(1)

print("Los dos formatos de 'codigo_reporte':")
print(_perfil.to_string(index=False))

_n_ai = int(_perfil.loc[_perfil["formato_codigo"] == "prefijo AI", "reportes"].iloc[0])
_n_num = int(_perfil.loc[_perfil["formato_codigo"] == "numerico", "reportes"].iloc[0])
_pct_ai = float(_perfil.loc[_perfil["formato_codigo"] == "prefijo AI",
                            "% con numero_vehiculos"].iloc[0])
_pct_num = float(_perfil.loc[_perfil["formato_codigo"] == "numerico",
                             "% con numero_vehiculos"].iloc[0])
_pct_rep_ai = float(_perfil.loc[_perfil["formato_codigo"] == "prefijo AI",
                                "% de los reportes"].iloc[0])
_pct_rep_num = float(_perfil.loc[_perfil["formato_codigo"] == "numerico",
                                 "% de los reportes"].iloc[0])

display(Markdown(f"""
### 2. ¿Qué aporta la clave subrogada?

El hecho tiene {fmt(n_filas)} filas y su PK es un entero que va de 1 a
{fmt(n_filas)}. `codigo_reporte` es único, así que *técnicamente* podría ser la
clave primaria. La razón para no usarlo no es teórica: está en los datos.

**La evidencia: el código no es un solo sistema.** `codigo_reporte` llega en
dos formatos, y no se comportan igual:

- **{fmt(_n_num)} reportes ({_pct_rep_num} %)**
  con código numérico, de los cuales el **{_pct_num} %** trae `numero_vehiculos`.
- **{fmt(_n_ai)} reportes ({_pct_rep_ai} %)**
  con prefijo `AI`, de los cuales solo el **{_pct_ai} %** trae esa medida.

Son dos poblaciones con una diferencia de **{abs(_pct_ai - _pct_num):.1f} puntos
porcentuales** en la disponibilidad de la medida. Un identificador que no
identifica un tipo de registro sino dos, con comportamientos distintos, no es
una clave confiable: obliga a cada consumidor a hardcodear la regla del `AI`.

La clave subrogada (`id_siniestro`) aporta:

- **Homogeneidad**: `BIGINT` en vez de texto, más compacto y más rápido de
  indexar en un `JOIN` de {fmt(n_filas)} filas.
- **Un punto de entrada único** para enlazar el hecho con otras fuentes en la
  Fase C, sin arrastrar la convención de cada sistema de origen.
- **Desacoplo**: si la fuente renombra el prefijo `AI` o cambia el ancho del
  código numérico, la bodega no se entera.

El código se conserva, pero **degradado a atributo**: *describe* el reporte,
mientras que `id_siniestro` lo *identifica* dentro de la bodega. Esa es la
diferencia entre un atributo y una clave.
"""))

Los dos formatos de 'codigo_reporte':
formato_codigo  reportes  medida_informada     ejemplo  % con numero_vehiculos  % de los reportes
      numerico    357599            171190       96159                    47.9               96.4
    prefijo AI     13399              5387 AI000000030                    40.2                3.6

### 2. ¿Qué aporta la clave subrogada?

El hecho tiene 370,998 filas y su PK es un entero que va de 1 a
370,998. `codigo_reporte` es único, así que *técnicamente* podría ser la
clave primaria. La razón para no usarlo no es teórica: está en los datos.

**La evidencia: el código no es un solo sistema.** `codigo_reporte` llega en
dos formatos, y no se comportan igual:

- **357,599 reportes (96.4 %)**
  con código numérico, de los cuales el **47.9 %** trae `numero_vehiculos`.
- **13,399 reportes (3.6 %)**
  con prefijo `AI`, de los cuales solo el **40.2 %** trae esa medida.

Son dos poblaciones con una diferencia de **7.7 puntos
porcentuales** en la disponibilidad de la medida. Un identificador que no
identifica un tipo de registro sino dos, con comportamientos distintos, no es
una clave confiable: obliga a cada consumidor a hardcodear la regla del `AI`.

La clave subrogada (`id_siniestro`) aporta:

- **Homogeneidad**: `BIGINT` en vez de texto, más compacto y más rápido de
  indexar en un `JOIN` de 370,998 filas.
- **Un punto de entrada único** para enlazar el hecho con otras fuentes en la
  Fase C, sin arrastrar la convención de cada sistema de origen.
- **Desacoplo**: si la fuente renombra el prefijo `AI` o cambia el ancho del
  código numérico, la bodega no se entera.

El código se conserva, pero **degradado a atributo**: *describe* el reporte,
mientras que `id_siniestro` lo *identifica* dentro de la bodega. Esa es la
diferencia entre un atributo y una clave.

In [124]:
# --- Reflexion 3: que tan comparable es 2016-2024? -------------------------
cobertura = RANGO["filas"]

_volumen = por_anio.set_index("año")["reportes"]
_anio_pico = int(_volumen.idxmax())
_anio_valle = int(_volumen.idxmin())
_pico = int(_volumen.max())
_valle = int(_volumen.min())
_caida_pico_valle = (_valle - _pico) / _pico * 100
_salto_2020 = float(por_anio.loc[por_anio["año"] == 2020,
                                 "variación vs año anterior"].iloc[0])
_caida_hasta_valle = float(por_anio.loc[por_anio["año"] == _anio_valle,
                                       "variación vs año anterior"].iloc[0])

_pct_medida_nula = float(w["numero_vehiculos"].isna().mean() * 100)
_disp = disp_por_anio.set_index("anio")["% informado"]

display(Markdown(f"""
### 3. ¿Es comparable el periodo 2016–{RANGO['fin'].year}?

**No, y la Fase C tiene que saberlo antes de comparar años.**

Los datos van del **{RANGO['inicio']}** al **{RANGO['fin']}**, con
{fmt(cobertura)} reportes. Hay dos problemas distintos, y el segundo es el
que menos se ve.

**El último año está incompleto.** {ULTIMO_ANIO} llega hasta el
{FECHA_MAX.date()}, que es el {DIA_MES_ULTIMO} de {MES_ULTIMO.lower()}. No "hasta el mes 11"
— son dos días. Cualquier ranking por volumen deja a {ULTIMO_ANIO} último de
forma artificial. Use la columna `reportes por dia cubierto`, o compare solo
hasta {ULTIMO_COMPLETO}.

**El volumen tampoco es homogéneo, y esto no tiene nada que ver con las
fechas.** El pico es {_anio_pico} con {fmt(_pico)} reportes y el valle es
{_anio_valle} con {fmt(_valle)}: una caída del **{abs(_caida_pico_valle):.1f} %**.
El salto más grande está en 2020, con **{_salto_2020:.1f} %** respecto a 2019, y
el valle llega {abs(_caida_hasta_valle):.1f} % por debajo del año anterior. Es la firma de
un cambio de cobertura o de forma de reportar, no de menos accidentes: por eso
el conteo anual **tampoco** es una serie homogénea. Si la Fase C grafica
reportes por año sin decirlo, va a dibujar un problema de datos como
si fuera una tendencia real.

**Y la medida es la más débil de las tres.** `numero_vehiculos` llega nula en el
**{_pct_medida_nula:.1f} %** de los registros, y esa proporción va del
**{_disp.min():.1f} %** informado en {_disp.idxmin()} al **{_disp.max():.1f} %**
en {_disp.idxmax()}. Un promedio sobre un año con más cobertura no es
comparable con uno de un año con menos.

**Regla de uso:** para volumen, `reportes por dia cubierto` y solo años
completos (hasta {ULTIMO_COMPLETO}). Para medidas, considéralas indicadores de
**cobertura** y no promedios. Y documente siempre el corte: un número sin su
fecha máxima no es interpretable.
"""))

### 3. ¿Es comparable el periodo 2016–2024?

**No, y la Fase C tiene que saberlo antes de comparar años.**

Los datos van del **2016-01-01** al **2024-11-02**, con
370,998 reportes. Hay dos problemas distintos, y el segundo es el
que menos se ve.

**El último año está incompleto.** 2024 llega hasta el
2024-11-02, que es el 2 de noviembre. No "hasta el mes 11"
— son dos días. Cualquier ranking por volumen deja a 2024 último de
forma artificial. Use la columna `reportes por dia cubierto`, o compare solo
hasta 2023.

**El volumen tampoco es homogéneo, y esto no tiene nada que ver con las
fechas.** El pico es 2016 con 64,323 reportes y el valle es
2024 con 12,080: una caída del **81.2 %**.
El salto más grande está en 2020, con **-44.7 %** respecto a 2019, y
el valle llega 35.7 % por debajo del año anterior. Es la firma de
un cambio de cobertura o de forma de reportar, no de menos accidentes: por eso
el conteo anual **tampoco** es una serie homogénea. Si la Fase C grafica
reportes por año sin decirlo, va a dibujar un problema de datos como
si fuera una tendencia real.

**Y la medida es la más débil de las tres.** `numero_vehiculos` llega nula en el
**52.4 %** de los registros, y esa proporción va del
**31.9 %** informado en 2023 al **57.6 %**
en 2020. Un promedio sobre un año con más cobertura no es
comparable con uno de un año con menos.

**Regla de uso:** para volumen, `reportes por dia cubierto` y solo años
completos (hasta 2023). Para medidas, considéralas indicadores de
**cobertura** y no promedios. Y documente siempre el corte: un número sin su
fecha máxima no es interpretable.

---
## T3 — Qué se entrega

El modelo queda cargado y listo para la **Fase C**. Lo entregado:

| Elemento | Contenido |
|---|---|
| `hecho_siniestralidad` | un reporte por fila, con la medida y las 6 claves foráneas |
| `dim_fecha` | fecha, año, mes, trimestre, día de la semana y si es fin de semana |
| `dim_ubicacion` | dirección del reporte, normalizada |
| `dim_tipo_accidente` | tipo de accidente, con `SIN ACCIDENTE (NEGATIVO)` y `NO APLICA` |
| `dim_tipo_confirmado` | clasificación general y su detalle, con `SIN DETALLE` |
| `dim_medio_reporte` | medio de reporte, con `OTRO` fusionado y narrativas anonimizadas |
| `dim_vehiculos_implicados` | combinación canónica de vehículos + 3 columnas derivadas |
| Índices | uno por cada clave foránea del hecho |
| Control de calidad | reconciliación de nulos, integridad referencial, unicidad de PK |

### Riesgos y limitaciones asumidos

Las nueve limitaciones del modelo, con las cifras calculadas en la celda siguiente sobre los datos cargados.

In [125]:
_pct_medida_nula_lim = float(w["numero_vehiculos"].isna().mean() * 100)
_disp_lim = disp_por_anio.set_index("anio")["% informado"]
_min_ano = int(_disp_lim.idxmin())
_max_ano = int(_disp_lim.idxmax())

_pct_medio_nulo = float(w["medio_reporte"].isna().mean() * 100)
_pct_ta_desconocido = float((HECHO["id_tipo_accidente"] == -1).mean() * 100)
_n_no_aplica = int((w["tipo_accidente"] == ETIQUETA_NO_APLICA).sum())
_n_sin_accidente = int((w["tipo_accidente"] == ETIQUETA_SIN_ACCIDENTE).sum())

_pct_dir_nula = float(w["direccion_reporte"].isna().mean() * 100)
_n_dir_interrogacion = int(
    w["direccion_reporte"].str.contains(r"\?", regex=True, na=False).sum())

_n_narrativas = int(es_narrativa.sum())
_n_otro_valor = int(n_otro_fuente_solo)

_n_ai_lim = int(_perfil.loc[_perfil["formato_codigo"] == "prefijo AI", "reportes"].iloc[0])
_n_num_lim = int(_perfil.loc[_perfil["formato_codigo"] == "numerico", "reportes"].iloc[0])
_pct_ai_lim = float(_perfil.loc[_perfil["formato_codigo"] == "prefijo AI",
                                "% con numero_vehiculos"].iloc[0])
_pct_num_lim = float(_perfil.loc[_perfil["formato_codigo"] == "numerico",
                                 "% con numero_vehiculos"].iloc[0])

_mojibake_direccion = _n_dir_interrogacion

_n_duplicados = len(df_raw) - len(df) - descartadas_vacias
_filas_finales = len(HECHO)

_vol_lim = por_anio.set_index("año")["reportes"]
_caida_lim = float((_vol_lim.min() - _vol_lim.max()) / _vol_lim.max() * 100)

display(Markdown(f"""
### Riesgos y limitaciones asumidos

**1. `numero_vehiculos` está ausente en el {_pct_medida_nula_lim:.1f} % de los
reportes** y su disponibilidad va del {_disp_lim.min():.1f} % en {_min_ano} al
{_disp_lim.max():.1f} % en {_max_ano}. No se imputa. Los promedios de esa
columna no son comparables entre años; úsela como indicador de cobertura.

**2. `medio_reporte` es nulo en el {_pct_medio_nulo:.1f} %** de los reportes.
En `tipo_accidente`, el {_pct_ta_desconocido:.1f} % va a la centinela
`id = -1`, y hay dos grupos que **no** son "desconocido" sino estructura:
{fmt(_n_no_aplica)} filas `NO APLICA` (la fuente lo dice) y
{fmt(_n_sin_accidente)} `SIN ACCIDENTE (NEGATIVO)` (el reporte es negativo, así
que la ausencia de tipo es esperable). Colapsarlos sería mentir.

**3. `direccion_reporte` es nula en el {_pct_dir_nula:.1f} %** y conserva el
carácter `?` en **{fmt(_n_dir_interrogacion)} filas**. No se repara a propósito:
el `?` es la `Í` en `CL?NICA` y la `Ñ` en `Ca?asgordas`, y una regla global
arregla unas y rompe otras. Es texto libre; la dirección no se usa como clave.

**4. Hay dos sistemas de origen.** `codigo_reporte` llega en dos formatos:
{fmt(_n_num_lim)} numéricos y {fmt(_n_ai_lim)} con prefijo `AI`. No se
comportan igual: el {_pct_num_lim:.1f} % de los numéricos trae
`numero_vehiculos` y solo el {_pct_ai_lim:.1f} % de los `AI`. Cualquier
cruce por código debe tener esto en cuenta.

**5. El mojibake no se recupera fuera del diccionario.** Solo se reparan
{fmt(int(_tabla_norm['reparadas_por_diccionario'].sum()))} celdas con las
{int(len(MAPA_REPARACION))} reglas declaradas. El resto del `?` de los catálogos
queda como está, y las {_mojibake_direccion:,} filas de dirección quedan
completas sin reparar.

**6. PII en `medio_reporte`.** {_n_narrativas} celdas eran texto libre con
nombres, cédulas y placas, no un medio de reporte. Se remapean a `OTRO` y su
contenido no se carga: se pierden {_n_narrativas} registros de detalle a cambio
de no exponer datos personales. Junto a las {_n_otro_valor} filas `OTRO VALOR`
de la fuente, `OTRO` queda con {_n_narrativas + _n_otro_valor} filas.

**7. El dataset no pasa entero al hecho.** De {len(df_raw):,} filas crudas se
descarta **{descartadas_vacias} fila vacía** y **{_n_duplicados} duplicados
exactos** (mismas 10 columnas), y quedan **{fmt(_filas_finales)}** en el hecho.
Los duplicados se eliminan solo si son idénticos en todas las columnas: si dos
eventos distintos comparten código, ambos se conservan.

**8. La serie termina el {FECHA_MAX.date()}** ({MES_ULTIMO}, día
{DIA_MES_ULTIMO}) y el volumen cae un **{abs(_caida_lim):.1f} %** entre el año
pico y el valle. {ULTIMO_ANIO} no es comparable con los años completos: use
`reportes por dia cubierto` y compare hasta {ULTIMO_COMPLETO}.

**9. No hay `FOREIGN KEY` en el motor.** Las 6 FK se validan en el ETL y se
verifican después de cargar, pero PostgreSQL no las impone. Una carga externa
podría romper la integridad sin que la base lo impida. Las 7 PRIMARY KEY sí
están declaradas, así que la unicidad de los ids sí la garantiza el motor.
"""))

### Riesgos y limitaciones asumidos

**1. `numero_vehiculos` está ausente en el 52.4 % de los
reportes** y su disponibilidad va del 31.9 % en 2023 al
57.6 % en 2020. No se imputa. Los promedios de esa
columna no son comparables entre años; úsela como indicador de cobertura.

**2. `medio_reporte` es nulo en el 77.7 %** de los reportes.
En `tipo_accidente`, el 26.2 % va a la centinela
`id = -1`, y hay dos grupos que **no** son "desconocido" sino estructura:
2,885 filas `NO APLICA` (la fuente lo dice) y
227,937 `SIN ACCIDENTE (NEGATIVO)` (el reporte es negativo, así
que la ausencia de tipo es esperable). Colapsarlos sería mentir.

**3. `direccion_reporte` es nula en el 49.5 %** y conserva el
carácter `?` en **1,054 filas**. No se repara a propósito:
el `?` es la `Í` en `CL?NICA` y la `Ñ` en `Ca?asgordas`, y una regla global
arregla unas y rompe otras. Es texto libre; la dirección no se usa como clave.

**4. Hay dos sistemas de origen.** `codigo_reporte` llega en dos formatos:
357,599 numéricos y 13,399 con prefijo `AI`. No se
comportan igual: el 47.9 % de los numéricos trae
`numero_vehiculos` y solo el 40.2 % de los `AI`. Cualquier
cruce por código debe tener esto en cuenta.

**5. El mojibake no se recupera fuera del diccionario.** Solo se reparan
84,073 celdas con las
12 reglas declaradas. El resto del `?` de los catálogos
queda como está, y las 1,054 filas de dirección quedan
completas sin reparar.

**6. PII en `medio_reporte`.** 5 celdas eran texto libre con
nombres, cédulas y placas, no un medio de reporte. Se remapean a `OTRO` y su
contenido no se carga: se pierden 5 registros de detalle a cambio
de no exponer datos personales. Junto a las 9 filas `OTRO VALOR`
de la fuente, `OTRO` queda con 14 filas.

**7. El dataset no pasa entero al hecho.** De 371,003 filas crudas se
descarta **1 fila vacía** y **4 duplicados
exactos** (mismas 10 columnas), y quedan **370,998** en el hecho.
Los duplicados se eliminan solo si son idénticos en todas las columnas: si dos
eventos distintos comparten código, ambos se conservan.

**8. La serie termina el 2024-11-02** (NOVIEMBRE, día
2) y el volumen cae un **81.2 %** entre el año
pico y el valle. 2024 no es comparable con los años completos: use
`reportes por dia cubierto` y compare hasta 2023.

**9. No hay `FOREIGN KEY` en el motor.** Las 6 FK se validan en el ETL y se
verifican después de cargar, pero PostgreSQL no las impone. Una carga externa
podría romper la integridad sin que la base lo impida. Las 7 PRIMARY KEY sí
están declaradas, así que la unicidad de los ids sí la garantiza el motor.

---

*Fase B — Pipeline ETL · `[Integrantes del grupo N]` · RA1 · 30% de la nota*